// Giove, Saturno, Urano, Nettuno, Plutone nelle 12 case — en, it (registro tradizionale e psicologico, niente trading).
// Dignità per analogia casa-segno: I Ariete ... XII Pesci. D domicilio, E esaltazione, X esilio, F caduta, P peregrino.
// Urano, Nettuno, Plutone: assegnazioni moderne (la tradizione non ne ha), nessuna gioia (JOY = -1).
var TG = {
it:{dir:'ltr',title:'Giove nelle 12 case',sub:'Dove cresce, in cosa confida, dove dona',h:['Casa','Lettura','Dignità'],
 d:{D:['Domicilio','molto forte'],E:['Esaltazione','forte'],X:['Esilio','debole'],F:['Caduta','molto debole'],P:['Peregrino','neutro']},joy:'gioia',
 signs:['Ariete','Toro','Gemelli','Cancro','Leone','Vergine','Bilancia','Scorpione','Sagittario','Capricorno','Acquario','Pesci'],
 rows:[['Identità','Presenza aperta e generosa. Ispira fiducia; tende a promettere più del possibile.'],
 ['Denaro','Le risorse arrivano attraverso la fiducia e gli altri. Generoso, rischia di spendere sulla speranza.'],
 ['Mente e parola','Mente ampia, grandi idee. In esilio: il quadro generale vince sui dettagli.'],
 ['Casa e radici','Esaltato: una casa aperta e calda. Tradizioni di famiglia, una vita che si arricchisce.'],
 ['Piacere e creatività','Amore generoso, gioia nei figli e nelle feste. Il rischio è l\'eccesso.'],
 ['Lavoro quotidiano','In esilio: più compiti che tempo. Solleva il gruppo; attenzione agli eccessi.'],
 ['Legami e partner','Cresce attraverso partner e accordi. Vede il meglio negli altri, a volte troppo.'],
 ['Crisi e trasformazione','Si riprende bene dalle crisi. Aiuto dalle risorse altrui; fiducia nei finali.'],
 ['Idee e orizzonti','Domicilio: fede, studio, viaggi lontani. Un maestro che deve anche ascoltare.'],
 ['Carriera','In caduta: mete alte che chiedono struttura. Mentori e senso dello scopo.'],
 ['Amici e progetti','Molti amici, speranze contagiose. Qui la tradizione dice che Giove gioisce.'],
 ['Ciò che è nascosto','Domicilio: protezione silenziosa, compassione, fede interiore. Servono limiti chiari.']],
 angT:'Giove sugli angoli',ang:['Presenza generosa e sicura: fiducia a prima vista.','Una casa grande e aperta; radici che crescono nel tempo.','Crescita e buona sorte attraverso i partner.','Una carriera con visione: insegnamento, guida, fiducia pubblica.'],
 leg:'Dignità di Giove nel segno naturale di ogni casa (I Ariete … XII Pesci): è l\'analogia casa-segno. Nell\'XI casa Giove ha la sua gioia.',cta:'Tema natale gratuito'},
en:{dir:'ltr',title:'Jupiter in the 12 houses',sub:'Where it grows, what it trusts, where it gives',h:['House','Reading','Dignity'],
 d:{D:['Domicile','very strong'],E:['Exaltation','strong'],X:['Detriment','weak'],F:['Fall','very weak'],P:['Peregrine','neutral']},joy:'joy',
 signs:['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'],
 rows:[['Identity','An open, generous presence. Inspires trust; tends to promise more than a day holds.'],
 ['Money','Resources arrive through trust and through others. Generous; may spend on hope.'],
 ['Mind and speech','A broad mind, big ideas. In detriment: the big picture wins over the details.'],
 ['Home and roots','Exalted: an open, warm home. Family traditions and a life that grows richer.'],
 ['Pleasure and play','Generous love, joy in children and celebrations. Excess is the risk.'],
 ['Daily work','In detriment: more tasks than time. Lifts the team; pay attention to excess.'],
 ['Partners and bonds','Grows through partners and agreements. Sees the best in others, at times too much.'],
 ['Crisis and change','Recovers well from crises. Help through others\' resources; faith in endings.'],
 ['Ideas and horizons','Domicile: faith, study, distant journeys. A teacher who must also listen.'],
 ['Career','In its fall: high aims that need structure. Mentors and a sense of purpose.'],
 ['Friends and plans','Many friends, contagious hopes. Tradition says Jupiter rejoices here.'],
 ['What is hidden','Domicile: quiet protection, compassion, inner faith. Needs clear limits.']],
 angT:'Jupiter on the angles',ang:['A generous, confident presence: trust at first sight.','A large, open home; roots that grow with time.','Growth and good fortune through partners.','A career with vision: teaching, guidance, public trust.'],
 leg:'Jupiter\'s dignity in the natural sign of each house (1st Aries … 12th Pisces): the house–sign analogy. In the 11th house Jupiter has its joy.',cta:'Free natal chart'}
};
var DIGN_G = ['P','P','X','E','P','X','P','P','D','F','P','D'];
var JOY_G = 10; // indice 0-based della XI casa: gioia di Giove

var TSA = {
it:{dir:'ltr',title:'Saturno nelle 12 case',sub:'Dove mette alla prova, cosa costruisce, dove resiste',h:['Casa','Lettura','Dignità'],
 d:{D:['Domicilio','molto forte'],E:['Esaltazione','forte'],X:['Esilio','debole'],F:['Caduta','molto debole'],P:['Peregrino','neutro']},joy:'gioia',
 signs:['Ariete','Toro','Gemelli','Cancro','Leone','Vergine','Bilancia','Scorpione','Sagittario','Capricorno','Acquario','Pesci'],
 rows:[['Identità','In caduta: serio, riservato, più grande dei suoi anni. Sicurezza costruita piano.'],
 ['Denaro','Risorse lente e solide. Attento alle spese; paura di non avere abbastanza.'],
 ['Mente e parola','Mente riflessiva, parole misurate. Impara piano e a fondo; una scuola severa.'],
 ['Casa e radici','In esilio: casa vissuta come dovere, un genitore esigente. Costruisce la casa che non ha avuto.'],
 ['Piacere e creatività','In esilio: la gioia va meritata. Amore serio; creatività che passa per la disciplina.'],
 ['Lavoro quotidiano','Metodo, routine, competenza costruita negli anni. Attenzione alla stanchezza.'],
 ['Legami e partner','Esaltato: impegni seri, partner maturi e corretti. Legami fatti per durare.'],
 ['Crisi e trasformazione','Fatica a lasciare andare. Perdite che fanno maturare presto; calma davanti ai finali.'],
 ['Idee e orizzonti','Convinzioni messe alla prova, saggezza guadagnata. Studi faticosi che rendono di più.'],
 ['Carriera','Domicilio: ascesa lenta e costante. Responsabilità e autorità guadagnate nel tempo.'],
 ['Amici e progetti','Domicilio: pochi amici fedeli. Obiettivi concreti; un ruolo preciso nel gruppo.'],
 ['Ciò che è nascosto','Solitudine ben usata, disciplina interiore. Qui la tradizione dice che Saturno gioisce.']],
 angT:'Saturno sugli angoli',ang:['Presenza seria e riservata: rispetto prima del calore.','Radici pesanti; una casa costruita con fatica e tempo.','Partner maturi; impegni presi sul serio.','Una carriera costruita passo dopo passo: un\'autorità che dura.'],
 leg:'Dignità di Saturno nel segno naturale di ogni casa (I Ariete … XII Pesci): è l\'analogia casa-segno. Nella XII casa Saturno ha la sua gioia.',cta:'Tema natale gratuito'},
en:{dir:'ltr',title:'Saturn in the 12 houses',sub:'Where it tests, what it builds, where it endures',h:['House','Reading','Dignity'],
 d:{D:['Domicile','very strong'],E:['Exaltation','strong'],X:['Detriment','weak'],F:['Fall','very weak'],P:['Peregrine','neutral']},joy:'joy',
 signs:['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'],
 rows:[['Identity','In its fall: serious, reserved, older than its years. Confidence built slowly.'],
 ['Money','Slow, solid resources. Careful with spending; fear of lack even in good times.'],
 ['Mind and speech','A deliberate mind, measured words. Learns slowly and deeply; a strict school.'],
 ['Home and roots','In detriment: home felt as a duty, a demanding parent. Builds the home it lacked.'],
 ['Pleasure and play','In detriment: joy that must be earned. Serious love; creativity through discipline.'],
 ['Daily work','Method, routine, expertise built over years. Pay attention to tiredness.'],
 ['Partners and bonds','Exalted: serious commitments, fair and mature partners. Bonds built to last.'],
 ['Crisis and change','Hard to let go. Losses that bring early maturity; calm before endings.'],
 ['Ideas and horizons','Tested beliefs, earned wisdom. Studies that cost effort and give back more.'],
 ['Career','Domicile: a slow, steady rise. Responsibility and authority earned over time.'],
 ['Friends and plans','Domicile: few, loyal friends. Concrete goals; a precise role in the group.'],
 ['What is hidden','Solitude used well, inner discipline. Tradition says Saturn rejoices here.']],
 angT:'Saturn on the angles',ang:['A serious, reserved presence: respect before warmth.','Heavy roots; a home built with effort and time.','Mature partners; commitments taken seriously.','A career built step by step: authority that lasts.'],
 leg:'Saturn\'s dignity in the natural sign of each house (1st Aries … 12th Pisces): the house–sign analogy. In the 12th house Saturn has its joy.',cta:'Free natal chart'}
};
var DIGN_SA = ['F','P','P','X','X','P','E','P','P','D','D','P'];
var JOY_SA = 11; // indice 0-based della XII casa: gioia di Saturno

var TU = {
it:{dir:'ltr',title:'Urano nelle 12 case',sub:'Dove si libera, cosa cambia, dove sorprende',h:['Casa','Lettura','Dignità'],
 d:{D:['Domicilio','molto forte'],E:['Esaltazione','forte'],X:['Esilio','debole'],F:['Caduta','molto debole'],P:['Peregrino','neutro']},joy:'gioia',
 signs:['Ariete','Toro','Gemelli','Cancro','Leone','Vergine','Bilancia','Scorpione','Sagittario','Capricorno','Acquario','Pesci'],
 rows:[['Identità','Presenza originale e irrequieta. Scelte improvvise; ha bisogno di libertà per essere sé.'],
 ['Denaro','In caduta: entrate con svolte improvvise. Sicurezza nell\'adattarsi, non nel trattenere.'],
 ['Mente e parola','Mente a lampi, idee insolite. Impara meglio fuori dalle scuole tradizionali.'],
 ['Casa e radici','Famiglia insolita, traslochi improvvisi. Una casa inventata a modo proprio.'],
 ['Piacere e creatività','In esilio: amori improvvisi, creatività originale. In amore la routine lo annoia.'],
 ['Lavoro quotidiano','Ha bisogno di flessibilità. Reinventa i metodi; attenzione alla tensione nervosa.'],
 ['Legami e partner','Legami liberi, inizi e fini improvvisi. Ha bisogno di spazio nella coppia.'],
 ['Crisi e trasformazione','Esaltato: svolte improvvise che diventano risvegli. Curiosità per l\'inspiegato.'],
 ['Idee e orizzonti','Cambi radicali di convinzione. Percorsi alternativi, idee in anticipo sui tempi.'],
 ['Carriera','Svolte inattese, lavoro autonomo. Innovazione e riforma come vocazione.'],
 ['Amici e progetti','Domicilio: amici vari e insoliti. Gruppi che vogliono cambiare qualcosa.'],
 ['Ciò che è nascosto','Intuizioni a lampi, un ribelle interiore. Ha bisogno di silenzio per calmare la mente.']],
 angT:'Urano sugli angoli',ang:['Presenza insolita: si nota perché è diversa.','Radici instabili o anticonvenzionali; traslochi improvvisi.','Relazioni libere e inattese.','Carriera di cambi improvvisi, innovazione, autonomia.'],
 leg:'Assegnazioni moderne: la tradizione non dà dignità a Urano, e i pianeti esterni non hanno gioia. Analogia casa-segno (I Ariete … XII Pesci).',cta:'Tema natale gratuito'},
en:{dir:'ltr',title:'Uranus in the 12 houses',sub:'Where it breaks free, what it changes, where it surprises',h:['House','Reading','Dignity'],
 d:{D:['Domicile','very strong'],E:['Exaltation','strong'],X:['Detriment','weak'],F:['Fall','very weak'],P:['Peregrine','neutral']},joy:'joy',
 signs:['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'],
 rows:[['Identity','An original, restless presence. Sudden choices; needs freedom to be itself.'],
 ['Money','In its fall: income with sudden turns. Security through adapting, not holding on.'],
 ['Mind and speech','A mind that works in flashes, unusual ideas. Learns best outside the usual schools.'],
 ['Home and roots','An unusual family, sudden moves. A home invented in its own way.'],
 ['Pleasure and play','In detriment: sudden loves, original creativity. Routine in love bores it.'],
 ['Daily work','Needs flexible work. Reinvents methods; pay attention to nervous tension.'],
 ['Partners and bonds','Free bonds, sudden beginnings and endings. Needs space within the couple.'],
 ['Crisis and change','Exalted: sudden turns that become awakenings. Curious about the unexplained.'],
 ['Ideas and horizons','Radical changes of belief. Alternative paths, ideas ahead of their time.'],
 ['Career','Unexpected turns, independent work. Innovation and reform as a vocation.'],
 ['Friends and plans','Domicile: varied, unusual friends. Groups that want to change something.'],
 ['What is hidden','Intuitions like flashes, an inner rebel. Needs silence to calm the mind.']],
 angT:'Uranus on the angles',ang:['An unusual presence: noticed for being different.','Unstable or unconventional roots; sudden moves.','Free, unexpected relationships.','A career of sudden changes, innovation, independence.'],
 leg:'Modern assignments: tradition gives Uranus no dignities, and outer planets have no joy. House–sign analogy (1st Aries … 12th Pisces).',cta:'Free natal chart'}
};
var DIGN_U = ['P','F','P','P','X','P','P','E','P','P','D','P'];
var JOY_U = -1; // nessuna gioia per i pianeti esterni

var TN = {
it:{dir:'ltr',title:'Nettuno nelle 12 case',sub:'Dove sogna, cosa dissolve, dove ispira',h:['Casa','Lettura','Dignità'],
 d:{D:['Domicilio','molto forte'],E:['Esaltazione','forte'],X:['Esilio','debole'],F:['Caduta','molto debole'],P:['Peregrino','neutro']},joy:'gioia',
 signs:['Ariete','Toro','Gemelli','Cancro','Leone','Vergine','Bilancia','Scorpione','Sagittario','Capricorno','Acquario','Pesci'],
 rows:[['Identità','Presenza sognante e sfuggente. Assorbe gli umori e riceve le proiezioni altrui.'],
 ['Denaro','Il denaro scivola via. Dà valore al senso più che agli oggetti; servono conti chiari.'],
 ['Mente e parola','Pensa per immagini e atmosfere. Dono poetico; verificare i fatti, evitare malintesi.'],
 ['Casa e radici','Esaltato: la casa come rifugio, una storia di famiglia misteriosa o idealizzata.'],
 ['Piacere e creatività','Ama un ideale. Musica, arte, cinema; delusioni che insegnano chiarezza.'],
 ['Lavoro quotidiano','In esilio: lavori di aiuto, routine caotiche. Attenzione agli eccessi.'],
 ['Legami e partner','Idealizza il partner. Attratto da persone sensibili; rischio di sacrificarsi.'],
 ['Crisi e trasformazione','Confini che si dissolvono. Mistica, fusione profonda, crisi che risvegliano.'],
 ['Idee e orizzonti','Cercatore di infinito. Fede, mari lontani, intuizione più che manuali.'],
 ['Carriera','In caduta: un percorso incerto. Arte, cura e visione che chiedono una forma concreta.'],
 ['Amici e progetti','Amici e cause idealisti. Speranze generose, a volte vaghe.'],
 ['Ciò che è nascosto','Domicilio: mondo interiore vasto, sogni vividi, compassione. Serve un ponte col quotidiano.']],
 angT:'Nettuno sugli angoli',ang:['Presenza fluida e affascinante: gli altri vedono ciò che desiderano.','Radici idealizzate; la casa come santuario.','Partner idealizzati; un amore che chiede occhi aperti.','Carriera di arte, cura o visione; un\'immagine difficile da afferrare.'],
 leg:'Assegnazioni moderne: la tradizione non dà dignità a Nettuno, e i pianeti esterni non hanno gioia. Analogia casa-segno (I Ariete … XII Pesci).',cta:'Tema natale gratuito'},
en:{dir:'ltr',title:'Neptune in the 12 houses',sub:'Where it dreams, what it dissolves, where it inspires',h:['House','Reading','Dignity'],
 d:{D:['Domicile','very strong'],E:['Exaltation','strong'],X:['Detriment','weak'],F:['Fall','very weak'],P:['Peregrine','neutral']},joy:'joy',
 signs:['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'],
 rows:[['Identity','A dreamy, elusive presence. Absorbs moods and receives others\' projections.'],
 ['Money','Money slips away easily. Values meaning over objects; needs clear accounts.'],
 ['Mind and speech','Thinks in images and moods. A poetic gift; check facts, avoid misunderstandings.'],
 ['Home and roots','Exalted: home as a refuge, a mysterious or idealised family story.'],
 ['Pleasure and play','Loves an ideal. Music, art and film; disappointments that teach clarity.'],
 ['Daily work','In detriment: helping work, chaotic routines. Pay attention to excess.'],
 ['Partners and bonds','Idealises the partner. Drawn to sensitive people; risk of self-sacrifice.'],
 ['Crisis and change','Boundaries that dissolve. Mysticism, deep fusion, crises that awaken.'],
 ['Ideas and horizons','A seeker of the infinite. Faith, distant seas, intuition over textbooks.'],
 ['Career','In its fall: an uncertain path. Art, care and vision that need a concrete form.'],
 ['Friends and plans','Idealistic friends and causes. Generous hopes, at times vague.'],
 ['What is hidden','Domicile: a vast inner world, vivid dreams, compassion. Needs a bridge to daily life.']],
 angT:'Neptune on the angles',ang:['A fluid, charming presence: others see what they wish.','Idealised roots; home as a sanctuary.','Idealised partners; a love that asks for clear eyes.','A career of art, care or vision; an image hard to pin down.'],
 leg:'Modern assignments: tradition gives Neptune no dignities, and outer planets have no joy. House–sign analogy (1st Aries … 12th Pisces).',cta:'Free natal chart'}
};
var DIGN_N = ['P','P','P','E','P','X','P','P','P','F','P','D'];
var JOY_N = -1; // nessuna gioia per i pianeti esterni

var TP = {
it:{dir:'ltr',title:'Plutone nelle 12 case',sub:'Dove scava, cosa trasforma, dove esercita potere',h:['Casa','Lettura','Dignità'],
 d:{D:['Domicilio','molto forte'],E:['Esaltazione','forte'],X:['Esilio','debole'],F:['Caduta','molto debole'],P:['Peregrino','neutro']},joy:'gioia',
 signs:['Ariete','Toro','Gemelli','Cancro','Leone','Vergine','Bilancia','Scorpione','Sagittario','Capricorno','Acquario','Pesci'],
 rows:[['Identità','Presenza intensa e magnetica. Reinvenzioni totali; resiste a ogni controllo.'],
 ['Denaro','In esilio: crisi e rinascite intorno alle risorse. Sa ricostruire da zero.'],
 ['Mente e parola','Parole penetranti, mente indagatrice. Segreti custoditi e scoperti.'],
 ['Casa e radici','Segreti di famiglia o una figura dominante. Spezzare uno schema ereditato.'],
 ['Piacere e creatività','Esaltato: passione totale e creativa. Gelosia da domare; potere che crea.'],
 ['Lavoro quotidiano','Concentrazione ossessiva, lotte di potere sul lavoro. Attenzione allo stress trattenuto.'],
 ['Legami e partner','Legami intensi e trasformanti. Potere e fiducia al centro della coppia.'],
 ['Crisi e trasformazione','Domicilio: nessuna paura del buio. Crisi profonde, rinascite, intuito sugli altri.'],
 ['Idee e orizzonti','Crisi radicali di convinzione. Una verità cercata fino in fondo, senza compromessi.'],
 ['Carriera','Influenza reale, fini radicali e nuovi inizi. Rialzarsi dopo una caduta.'],
 ['Amici e progetti','In caduta: poche amicizie, intense. Gruppi che vogliono un cambiamento profondo.'],
 ['Ciò che è nascosto','Un mondo interiore profondo, segreti che riemergono. Trasformazione dal lavoro interiore.']],
 angT:'Plutone sugli angoli',ang:['Presenza intensa: magnetismo e controllo.','Radici profonde; segreti di famiglia e rinascite.','Partner potenti; legami che trasformano.','Carriera di influenza: salire, cadere, risalire.'],
 leg:'Assegnazioni moderne: la tradizione non dà dignità a Plutone, e i pianeti esterni non hanno gioia. Analogia casa-segno (I Ariete … XII Pesci).',cta:'Tema natale gratuito'},
en:{dir:'ltr',title:'Pluto in the 12 houses',sub:'Where it digs, what it transforms, where it holds power',h:['House','Reading','Dignity'],
 d:{D:['Domicile','very strong'],E:['Exaltation','strong'],X:['Detriment','weak'],F:['Fall','very weak'],P:['Peregrine','neutral']},joy:'joy',
 signs:['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'],
 rows:[['Identity','An intense, magnetic presence. Total reinventions; resists any control.'],
 ['Money','In detriment: crises and rebirths around resources. Can rebuild from zero.'],
 ['Mind and speech','Penetrating words, a probing mind. Secrets kept and uncovered.'],
 ['Home and roots','Family secrets or a dominant figure. Breaking an inherited pattern.'],
 ['Pleasure and play','Exalted: total, creative passion. Jealousy to master; power that creates.'],
 ['Daily work','Obsessive focus, power struggles at work. Pay attention to stress held inside.'],
 ['Partners and bonds','Intense, transforming bonds. Power and trust at the centre of the couple.'],
 ['Crisis and change','Domicile: unafraid of the dark. Deep crises, rebirths, insight into others.'],
 ['Ideas and horizons','Radical crises of belief. A truth sought to the bottom, without compromise.'],
 ['Career','Real influence, radical endings and new starts. Rising again after a fall.'],
 ['Friends and plans','In its fall: few, intense friendships. Groups that want deep change.'],
 ['What is hidden','A deep inner world, secrets that resurface. Transformation through inner work.']],
 angT:'Pluto on the angles',ang:['An intense presence: magnetism and control.','Deep roots; family secrets and rebirths.','Powerful partners; bonds that transform.','A career of influence: rising, falling, rising again.'],
 leg:'Modern assignments: tradition gives Pluto no dignities, and outer planets have no joy. House–sign analogy (1st Aries … 12th Pisces).',cta:'Free natal chart'}
};
var DIGN_P = ['P','X','P','P','E','P','P','D','P','P','F','P'];
var JOY_P = -1; // nessuna gioia per i pianeti esterni
