// Serie B — Marte, Giove, Saturno, Urano, Nettuno, Plutone nelle 12 case — en, it.
// Si carica dopo serieB_i18n.js. Regole: niente trading/mercati, mai prima persona plurale, niente nomi di divinità.
SB.marte = {
en:[
 [['You walk fast, talk fast and decide before others have finished thinking.','When you concentrate, people often think you are angry with them.','You would rather start something badly than wait for the perfect moment.','Competition switches you on, even in a friendly game of cards.','You lose patience with people who take ages to get to the point.'],'Mars in the 1st is in its own domicile. Your drive shows; take aim before you charge.'],
 [['For you money is something you win, not something you wait for.','You have made at least one big purchase just to prove you could.','You earn better when there is a challenge or a rival to beat.','You defend what is yours with a grit that surprises people around you.','When you lose money you get angrier with yourself than with bad luck.'],'Mars in the 2nd turns money into a battlefield. You win when you choose the battle.'],
 [['You answer back in a flash, and sometimes regret it a minute later.','A brother or sister was your first rival, at the table and in the yard.','Behind the wheel or on a bike you have strong opinions about everyone else.','You argue to win, even when you know you are only half right.','A good debate charges you up more than a quiet afternoon.'],'Mars in the 3rd gives your words an edge. Use it to clarify, not to wound.'],
 [['Home is where you argue the most and where you defend the most.','Tension with a parent pushed you towards independence early.','You fix, build or renovate things at home with your own hands.','Raised voices at the dinner table were part of your childhood.','You would defend your family from anyone, even when you are angry with them.'],'Mars in the 4th is in its fall. The fire is in the foundations; turn it into warmth.'],
 [['You fall for people who are a challenge, not for the easy ones.','Sport, games and challenges with friends are how you let off steam.','You take risks for fun that others would take only if they had to.','In love you chase hard, then lose interest if the chase ends too soon.','With children you play hard, run around and laugh out loud.'],'Mars in the 5th plays to win. Passion is your fuel; choose games worth playing.'],
 [['Sitting idle when there is a job to be done is impossible for you.','You work faster than your colleagues and get impatient when they slow down.','A day of physical activity leaves you calmer than a day of rest.','You clash with bosses who give orders without knowing the job.','Pay attention to the stress you build up; you tend to ignore it until it shouts.'],'Mars in the 6th is in its joy. Work is where your fire becomes useful.'],
 [['You are drawn to strong, independent partners who do not back down.','Your relationships are lively, with honest arguments rather than silent grudges.','You have had at least one open rival who pushed you to grow.','You defend your partner fiercely, even when you disagree with them in private.','Too much harmony in a couple makes you suspect something is being hidden.'],'Mars in the 7th is in detriment. The other is your mirror; a fair contest can bring you closer.'],
 [['In a real crisis you keep calm while everyone else panics.','You do not forgive a betrayal easily, and you do not forget it.','Intense experiences attract you more than comfortable ones.','You would rather face a hard truth than live with a gentle lie.','Shared money or an inheritance has caused conflict in your family.'],'Mars in the 8th is in its own domicile. Your courage grows where others feel fear.'],
 [['You defend your beliefs with passion, sometimes with more heat than needed.','You travel to test yourself, not only to rest.','Rebelling against a teacher or a doctrine shaped the way you think.','You get heated in discussions about religion, politics or justice.','You prefer adventurous journeys to organised tours, even if they go wrong.'],'Mars in the 9th fights for an idea. Check that the idea is still worth the fight.'],
 [['You want a role where you decide, not one where you wait for orders.','You built your reputation with an effort that everyone could see.','You do your best work under pressure, with deadlines that scare your colleagues.','Authority figures either respect you or clash with you, with little in between.','An unfair boss once pushed you to prove what you are worth.'],'Mars in the 10th is exalted. Ambition is your engine; steer it with integrity.'],
 [['You are the one who organises the group and gets it moving.','Your friendships are loyal and lively, with the occasional heated argument.','You join a cause to do something, not just to talk about it.','You lose patience with friends who make plans and never follow through.','You have ended at least one friendship over a question of principle.'],'Mars in the 11th fights for the group. Choose allies who share your goal.'],
 [['You keep your anger inside until it comes out all at once.','You work hardest on the projects nobody sees.','Open conflict makes you uneasy, so you fight in quieter ways.','At times you sense hostility from people who never show it openly.','A solitary activity, like running or swimming, clears your head better than talking.'],'Mars in the 12th is a hidden fire. Give it a channel before it burns inside.']
],
it:[
 [['Cammini veloce, parli veloce e decidi prima che gli altri abbiano finito di pensare.','Quando ti concentri, gli altri scambiano la tua espressione per rabbia.','Preferisci cominciare male piuttosto che aspettare il momento perfetto.','La competizione ti accende, anche in una partita a carte tra amici.','Perdi la pazienza con chi impiega ore ad arrivare al punto.'],'Marte in prima è in domicilio. La tua spinta si vede: prendi la mira prima di partire.'],
 [['Il denaro per te è una conquista, non un\'attesa.','Hai fatto almeno un acquisto importante solo per dimostrare che potevi.','Guadagni meglio quando c\'è una sfida o un rivale da battere.','Difendi ciò che è tuo con una grinta che sorprende chi ti sta intorno.','Quando perdi soldi ti arrabbi più con te stesso che con la sfortuna.'],'Marte in seconda trasforma il denaro in un campo di battaglia. Vinci quando la battaglia la scegli tu.'],
 [['Rispondi a tono in un attimo, e a volte te ne penti un minuto dopo.','Un fratello o una sorella è stato il tuo primo rivale, a tavola e in cortile.','Al volante o in bici hai opinioni forti su tutti gli altri.','Discuti per vincere, anche quando sai di avere ragione solo a metà.','Un bel dibattito ti carica più di un pomeriggio tranquillo.'],'Marte in terza dà un filo tagliente alle parole. Usalo per chiarire, non per ferire.'],
 [['La casa è il posto dove litighi di più e dove difendi di più.','Le tensioni con un genitore hanno accelerato la tua indipendenza.','Aggiusti, costruisci o ristrutturi le cose di casa con le tue mani.','Le voci alzate a tavola facevano parte della tua infanzia.','Difenderesti la tua famiglia da chiunque, anche quando sei in collera con lei.'],'Marte in quarta è in caduta. Il fuoco è nelle fondamenta: trasformalo in calore.'],
 [['Ti innamori di chi è una sfida, non di chi è facile.','Sport, giochi e sfide tra amici sono il tuo modo di scaricarti.','Per divertimento corri rischi che altri correrebbero solo per necessità.','In amore insegui con forza, poi perdi interesse se la conquista finisce troppo presto.','Con i bambini giochi forte, corri e ridi a voce alta.'],'Marte in quinta gioca per vincere. La passione è il tuo carburante: scegli giochi che valgono.'],
 [['Stare con le mani in mano, quando c\'è un lavoro da fare, ti è impossibile.','Lavori più in fretta dei colleghi e ti spazientisci quando rallentano.','Una giornata di attività fisica ti calma più di una giornata di riposo.','Ti scontri con i capi che danno ordini senza conoscere il lavoro.','Fai attenzione allo stress che accumuli: tendi a ignorarlo finché non alza la voce.'],'Marte in sesta è nella sua gioia. Il lavoro è dove il tuo fuoco diventa utile.'],
 [['Ti attraggono partner forti e indipendenti, che non si tirano indietro.','Le tue relazioni sono vivaci, con discussioni sincere invece di rancori muti.','Hai avuto almeno un rivale dichiarato che ti ha spinto a crescere.','Difendi il partner con forza, anche quando in privato non sei d\'accordo.','Troppa armonia in coppia ti fa sospettare che qualcosa venga nascosto.'],'Marte in settima è in esilio. L\'altro è il tuo specchio: un confronto leale può avvicinarvi.'],
 [['In una vera crisi mantieni la calma mentre gli altri vanno nel panico.','Non perdoni facilmente un tradimento, e non lo dimentichi.','Le esperienze intense ti attirano più di quelle comode.','Preferisci affrontare una verità dura che vivere con una bugia gentile.','Soldi condivisi o un\'eredità sono stati motivo di conflitto in famiglia.'],'Marte in ottava è in domicilio. Il tuo coraggio cresce dove gli altri hanno paura.'],
 [['Difendi le tue convinzioni con passione, a volte con più foga del necessario.','Viaggi per metterti alla prova, non solo per riposare.','Ribellarti a un insegnante o a una dottrina ha formato il tuo modo di pensare.','Ti accendi nelle discussioni su religione, politica o giustizia.','Preferisci i viaggi avventurosi ai tour organizzati, anche quando qualcosa va storto.'],'Marte in nona combatte per un\'idea. Verifica che l\'idea valga ancora la battaglia.'],
 [['Vuoi un ruolo in cui decidi tu, non uno in cui aspetti ordini.','Hai costruito la tua reputazione con un impegno che tutti hanno visto.','Rendi al meglio sotto pressione, con scadenze che spaventano i colleghi.','Con le figure d\'autorità o c\'è rispetto o c\'è scontro, raramente vie di mezzo.','Un capo ingiusto ti ha dato la spinta a dimostrare quanto vali.'],'Marte in decima è in esaltazione. L\'ambizione è il tuo motore: guidala con integrità.'],
 [['Sei tu che organizzi il gruppo e lo spingi all\'azione.','Le tue amicizie sono leali e vivaci, con qualche discussione accesa.','Ti unisci a una causa per fare qualcosa, non solo per parlarne.','Perdi la pazienza con gli amici che fanno piani e non li portano a termine.','Hai chiuso almeno un\'amicizia per una questione di principio.'],'Marte in undicesima combatte per il gruppo. Scegli alleati che condividono la tua meta.'],
 [['Tieni la rabbia dentro finché non esce tutta in una volta.','Lavori con più forza ai progetti che nessuno vede.','Il conflitto aperto ti mette a disagio, così combatti in modi più silenziosi.','A volte senti un\'ostilità da persone che non la mostrano mai apertamente.','Un\'attività in solitaria, come correre o nuotare, ti schiarisce la testa più di una chiacchierata.'],'Marte in dodicesima è un fuoco nascosto. Dagli un canale prima che bruci dentro.']
]};

SB.giove = {
en:[
 [['People trust you quickly, often before you have done anything to earn it.','You tend to promise a little more than a single day can hold.','Your optimism lifts a room, even on a grey morning.','Generosity is your first instinct, sometimes before you check your own resources.','Rules that feel too narrow make you restless and a little rebellious.'],'Jupiter in the 1st widens everything you touch. Leave some room for limits.'],
 [['Money comes and goes easily, and you rarely panic when it goes.','Gifts, dinners and invitations: your generosity is big, sometimes too big.','For you wealth means being able to share, not being able to save.','You make big plans and sometimes spend on hope rather than on facts.','Resources tend to arrive when you need them, often through other people.'],'Jupiter in the 2nd trusts abundance. Gratitude and a clear budget make it real.'],
 [['You know a little about everything and love to share it.','You start more books, courses and conversations than you finish.','Siblings, cousins or neighbours have been a real source of support.','You enlarge a story to make it better, and everyone enjoys it.','Details bore you when you can already see the big picture.'],'Jupiter in the 3rd is in detriment. Big ideas need checked facts before you spread them.'],
 [['Your home is open, full of people, food and conversation.','At least one of your parents was generous or larger than life.','You dream of a bigger house, a garden or more room to breathe.','Family traditions matter to you, and you keep them alive.','Your life tends to grow fuller and richer as the years go by.'],'Jupiter in the 4th is exalted. Your roots feed you; share the table.'],
 [['You love generously and enjoy making the people you love feel special.','Holidays, parties and celebrations are where you shine.','Children, or teaching younger people, bring you real joy.','You tend to overdo pleasures: one more dessert, one more trip, one more night out.','Your creativity grows when someone believes in it.'],'Jupiter in the 5th makes joy generous. Enjoy it, and know when it is enough.'],
 [['You take on more work than you can handle because you hate saying no.','Colleagues like working with you because you lift the mood.','You prefer flexible routines to rigid timetables that never change.','Pay attention to excess, because your body notices it before you do.','You find meaning in helping others in small, practical ways.'],'Jupiter in the 6th is in detriment. Grow through daily care, not through too much.'],
 [['You attract partners who are generous, cultured or from another background.','Your relationships help you grow, and you help your partner grow too.','You tend to see the best in people, sometimes ignoring the warning signs.','Agreements and partnerships have opened doors for you.','You believe in second chances, sometimes one too many.'],'Jupiter in the 7th finds good fortune through others. Choose people who grow with you.'],
 [['You recover from crises faster than people expect.','Help has reached you through a partner, a family or other people\'s resources.','Psychology, esoteric studies or deep research fascinate you.','You find meaning in experiences that others would rather avoid.','You trust that an ending makes room for something better.'],'Jupiter in the 8th finds abundance in depth. What you let go of makes room.'],
 [['You need a philosophy, a faith or a big idea to live by.','You feel at home in other countries, languages and cultures.','Studying something new excites you at any age.','People often ask you for advice, and you give it gladly.','When you are very sure you are right, you risk sounding like a sermon.'],'Jupiter in the 9th is in its own domicile. Meaning is your compass; listen as much as you teach.'],
 [['You aim high, and people often see you as a guide.','A mentor or an influential person helped your career at a key moment.','You want work that means something, not just a title.','Success can bring high expectations that are hard to carry.','You risk taking on too many roles at once to keep everyone happy.'],'Jupiter in the 10th is in its fall. Success asks for structure; build it step by step.'],
 [['You have many friends, and they come from very different worlds.','Friends have opened doors for you that you could not have opened without them.','You believe in the future, and your hopes are contagious.','Groups, associations and causes give you a sense of purpose.','Sometimes you say yes to too many invitations and too many plans.'],'Jupiter in the 11th is in its joy. Your circle is your good fortune.'],
 [['In hard moments you have felt as if someone were watching over you.','Silence, retreat or spiritual practice recharge you deeply.','You help people quietly, without telling anyone about it.','Your compassion is wide, and sometimes you forget your own limits.','Your best intuitions arrive in moments of solitude.'],'Jupiter in the 12th is in its own domicile. A quiet faith protects you; protect your limits too.']
],
it:[
 [['Le persone si fidano di te in fretta, spesso prima che tu abbia fatto qualcosa.','Tendi a promettere un po\' più di quanto una giornata possa contenere.','Il tuo ottimismo solleva una stanza, anche in una mattina grigia.','La generosità è il tuo primo istinto, a volte prima di controllare le tue risorse.','Le regole troppo strette ti mettono addosso irrequietezza e voglia di ribellarti.'],'Giove in prima allarga tutto ciò che tocca. Lascia un po\' di spazio ai limiti.'],
 [['Il denaro va e viene con facilità, e raramente ti fa prendere il panico.','Regali, cene e inviti: la tua generosità è grande, a volte anche troppo.','La ricchezza, per te, è poter condividere, non mettere da parte.','Fai progetti grandi e a volte spendi sulla speranza più che sui fatti.','Le risorse tendono ad arrivare quando servono, spesso attraverso altre persone.'],'Giove in seconda ha fiducia nell\'abbondanza. Gratitudine e un bilancio chiaro la rendono concreta.'],
 [['Sai un po\' di tutto e ami condividerlo.','Inizi più libri, corsi e conversazioni di quanti ne finisci.','Fratelli, cugini o vicini sono stati un vero sostegno per te.','Ingrandisci un racconto per renderlo migliore, e tutti si divertono.','I dettagli ti annoiano quando vedi già il quadro generale.'],'Giove in terza è in esilio. Le grandi idee chiedono fatti verificati prima di diffonderle.'],
 [['La tua casa è aperta, piena di persone, cibo e conversazioni.','Almeno uno dei tuoi genitori era generoso o fuori misura.','Sogni una casa più grande, un giardino o più spazio per respirare.','Le tradizioni di famiglia contano per te, e le tieni vive.','La tua vita tende a diventare più piena e ricca con il passare degli anni.'],'Giove in quarta è in esaltazione. Le radici ti nutrono: condividi la tavola.'],
 [['Ami con generosità e ti piace far sentire speciali le persone che ami.','Feste, vacanze e celebrazioni sono il tuo momento.','I bambini, o insegnare ai più giovani, ti danno una gioia vera.','Tendi a esagerare con i piaceri: un dolce in più, un viaggio in più, una serata in più.','La tua creatività cresce quando qualcuno ci crede.'],'Giove in quinta rende la gioia generosa. Goditela, e riconosci quando basta.'],
 [['Ti carichi di più lavoro del dovuto perché odi dire di no.','Ai colleghi piace lavorare con te perché alzi il morale.','Preferisci routine flessibili a orari rigidi che non cambiano mai.','Fai attenzione agli eccessi: il corpo se ne accorge prima di te.','Trovi senso nell\'aiutare gli altri in modi piccoli e pratici.'],'Giove in sesta è in esilio. Cresci attraverso la cura quotidiana, non attraverso il troppo.'],
 [['Ti attraggono partner generosi, colti o di un\'altra cultura.','Le relazioni ti fanno crescere, e tu fai crescere il partner.','Tendi a vedere il meglio nelle persone, a volte ignorando i segnali d\'allarme.','Accordi e collaborazioni ti hanno aperto delle porte.','Credi nelle seconde possibilità, a volte una di troppo.'],'Giove in settima trova fortuna attraverso gli altri. Scegli chi cresce con te.'],
 [['Ti riprendi dalle crisi più in fretta di quanto gli altri si aspettino.','L\'aiuto ti è arrivato da un partner, da una famiglia o dalle risorse di altri.','Psicologia, esoterismo o ricerca profonda ti affascinano.','Trovi senso in esperienze che altri preferirebbero evitare.','Hai fiducia che una fine faccia spazio a qualcosa di meglio.'],'Giove in ottava trova abbondanza nella profondità. Ciò che lasci andare fa spazio.'],
 [['Hai bisogno di una filosofia, di una fede o di una grande idea per vivere.','Ti senti a casa in altri paesi, lingue e culture.','Studiare qualcosa di nuovo ti entusiasma a ogni età.','Ti chiedono spesso consiglio, e lo dai volentieri.','Quando hai la certezza di avere ragione, rischi il tono della predica.'],'Giove in nona è in domicilio. Il senso è la tua bussola: ascolta quanto insegni.'],
 [['Punti in alto, e gli altri ti vedono spesso come una guida.','Un mentore o una persona influente ha aiutato la tua carriera in un momento chiave.','Vuoi un lavoro che abbia un senso, non solo un titolo.','Il successo può portare aspettative alte e difficili da reggere.','Rischi di prendere troppi ruoli insieme per accontentare tutti.'],'Giove in decima è in caduta. Il successo chiede struttura: costruiscila un passo alla volta.'],
 [['Hai molti amici, e vengono da mondi molto diversi.','Gli amici ti hanno aperto porte che non avresti aperto senza di loro.','Credi nel futuro, e le tue speranze sono contagiose.','Gruppi, associazioni e cause ti danno uno scopo.','A volte dici sì a troppi inviti e a troppi progetti.'],'Giove in undicesima è nella sua gioia. La tua cerchia è la tua fortuna.'],
 [['Nei momenti difficili hai avuto la sensazione che qualcuno vegliasse su di te.','Silenzio, ritiro o pratica spirituale ti ricaricano a fondo.','Aiuti le persone in silenzio, senza raccontarlo a nessuno.','La tua compassione è ampia, e a volte dimentichi i tuoi limiti.','Le intuizioni migliori ti arrivano nei momenti di solitudine.'],'Giove in dodicesima è in domicilio. Una fede silenziosa ti protegge: proteggi anche i tuoi limiti.']
]};

SB.saturno = {
en:[
 [['People think you are older or more serious than you really are.','Responsibilities came to you early, sometimes before you were ready.','In new situations you hold back until you understand the rules.','The harshest judge of what you do is usually you.','Confidence comes to you slowly, and once it comes it stays.'],'Saturn in the 1st is in its fall. Your seriousness is armour; you can take it off with people you trust.'],
 [['You keep an eye on every expense, even when there is no need.','Money came to you slowly, and you value every part of it.','You prefer things that last, even if they cost more effort to get.','The fear of not having enough can stay with you even in good times.','Your sense of worth grows with every skill you master.'],'Saturn in the 2nd builds slowly and solidly. Security is a habit, not a sum.'],
 [['You think before you speak, and you choose your words with care.','School meant hard work, or a teacher who was very strict.','Your bond with a brother or sister is complicated or distant.','You prefer one well-written message to ten hasty ones.','You learn slowly but deeply, and you do not forget.'],'Saturn in the 3rd gives weight to words. Your thinking matures with time.'],
 [['In your childhood, home felt more like a duty than a refuge.','A parent was strict, absent or carried too much on their shoulders.','You look after your family in practical ways, rarely with big gestures.','Having a home that is truly yours is one of your deepest goals.','You find it hard to ask your family for help.'],'Saturn in the 4th is in detriment. You can build the home you did not have.'],
 [['Having fun does not come naturally; you often feel you must earn it.','You take love seriously, and you do not give your heart easily.','Children, your own or other people\'s, awaken your sense of responsibility.','Your creativity needs discipline and time to show its real value.','The seriousness of your childhood has made room for lightness over the years.'],'Saturn in the 5th is in detriment. Joy is a skill too; practise it.'],
 [['You work hard and rarely allow yourself to slow down.','You like routines, lists and methods that actually work.','You feel responsible for mistakes even when they are not yours.','Pay attention to the signals of tiredness, because you tend to ignore them.','You reach mastery in your field through years of steady practice.'],'Saturn in the 6th turns work into a craft. Discipline is your strength, and rest is part of it.'],
 [['You take commitments seriously and do not make promises lightly.','You are drawn to partners who are older, mature or reliable.','Relationships came later for you, or after a hard lesson.','You expect fairness, and you give it back in return.','You read contracts and agreements twice before signing them.'],'Saturn in the 7th is exalted. Your bonds are built to last.'],
 [['Letting go is hard for you, whether of people, things or old pain.','Trusting someone with your deepest fears can take you years.','At least one loss made you grow up quickly.','Shared money or a partner\'s debts have taught you a hard lesson.','In the face of endings that frighten others, you keep calm.'],'Saturn in the 8th teaches through endings. What you face, you master.'],
 [['You question beliefs before you accept them, including your own.','Your studies cost you more time and effort than others, and gave you more.','A journey needs a purpose for you, not just a holiday.','You respect teachers who have earned their authority.','Your philosophy of life grew slowly, from experience rather than from books.'],'Saturn in the 9th seeks a truth that holds. Your wisdom is earned.'],
 [['You knew early on that you wanted to build something that lasts.','Your career grew slowly, step by step, but on solid ground.','People see you as reliable and hand you responsibility.','You feel the weight of expectations, especially your own.','Recognition often comes late for you, but it stays.'],'Saturn in the 10th is in its own domicile. Your patience becomes authority.'],
 [['You have few friends, but they have been with you for years.','In a group you feel more at ease when you have a precise role.','You often take on the job of organising friends or associations.','Your goals are concrete, and you plan them in detail.','At times you have felt out of place in a group.'],'Saturn in the 11th is in its own domicile. Loyal friendships are your solid ground.'],
 [['You need solitude, and you know how to use it well.','You carry worries that you do not share with anyone.','You work best behind the scenes, with patience and method.','Old fears return in quiet moments, and you have learned to face them.','A spiritual or inner discipline gives you a structure that holds.'],'Saturn in the 12th is in its joy. Solitude is where you find your solid ground.']
],
it:[
 [['Gli altri ti attribuiscono più anni e più serietà di quelli che hai.','Le responsabilità sono arrivate presto, a volte prima del tempo.','Nelle situazioni nuove ti trattieni finché non capisci le regole.','Il giudizio più severo su ciò che fai è quasi sempre il tuo.','La sicurezza arriva piano, e quando arriva resta.'],'Saturno in prima è in caduta. La serietà è un\'armatura: puoi toglierla con chi merita fiducia.'],
 [['Tieni d\'occhio ogni spesa, anche quando non ce n\'è bisogno.','Il denaro è arrivato piano, e ne apprezzi ogni parte.','Preferisci le cose che durano, anche se costano più fatica.','La paura di non avere abbastanza può restare anche nei periodi buoni.','Il senso del tuo valore cresce con ogni competenza che padroneggi.'],'Saturno in seconda costruisce piano e solido. La sicurezza è un\'abitudine, non una cifra.'],
 [['Pensi prima di parlare e scegli le parole con cura.','La scuola è stata fatica, o un insegnante molto severo.','Il rapporto con un fratello o una sorella è complicato o distante.','Preferisci un messaggio scritto bene a dieci scritti di fretta.','Impari piano ma a fondo, e non dimentichi.'],'Saturno in terza dà peso alle parole. Il tuo pensiero matura con il tempo.'],
 [['Nella tua infanzia la casa era più un dovere che un rifugio.','Un genitore era severo, assente o portava troppo sulle spalle.','Ti prendi cura della famiglia in modo pratico, raramente con grandi gesti.','Avere una casa davvero tua è uno dei tuoi obiettivi più profondi.','Ti costa chiedere aiuto alla tua famiglia.'],'Saturno in quarta è in esilio. Puoi costruire la casa che non hai avuto.'],
 [['Divertirti non ti viene naturale: spesso senti di doverlo meritare.','Prendi l\'amore sul serio e non dai il cuore facilmente.','I bambini, tuoi o di altri, risvegliano il tuo senso di responsabilità.','La tua creatività ha bisogno di disciplina e di tempo per mostrare il suo valore.','La serietà dell\'infanzia, con gli anni, ha lasciato spazio alla leggerezza.'],'Saturno in quinta è in esilio. Anche la gioia è un\'abilità: allenala.'],
 [['Lavori sodo e raramente ti concedi di rallentare.','Ti piacciono routine, liste e metodi che funzionano davvero.','Ti senti responsabile degli errori anche quando non sono tuoi.','Fai attenzione ai segnali di stanchezza, perché tendi a ignorarli.','Nel tuo campo arrivi alla maestria con anni di pratica costante.'],'Saturno in sesta fa del lavoro un mestiere. La disciplina è la tua forza, e il riposo ne fa parte.'],
 [['Prendi gli impegni sul serio e non fai promesse alla leggera.','Ti attraggono partner più grandi, maturi o affidabili.','Le relazioni sono arrivate tardi, o dopo una lezione dura.','Pretendi correttezza, e la restituisci.','Contratti e accordi li leggi due volte prima di firmare.'],'Saturno in settima è in esaltazione. I tuoi legami sono fatti per durare.'],
 [['Ti costa lasciare andare: persone, cose o vecchi dolori.','Confidare a qualcuno le tue paure più profonde può richiederti anni.','Almeno una perdita ti ha fatto crescere in fretta.','Soldi condivisi o debiti di un partner ti hanno dato una lezione dura.','Davanti a finali che spaventano gli altri, mantieni la calma.'],'Saturno in ottava insegna attraverso i finali. Ciò che affronti, lo padroneggi.'],
 [['Metti in discussione le credenze prima di accettarle, anche le tue.','Gli studi ti sono costati più tempo e fatica degli altri, e ti hanno dato di più.','Per te un viaggio ha bisogno di uno scopo, non solo di una vacanza.','Rispetti gli insegnanti che si sono guadagnati la loro autorità.','La tua filosofia di vita è nata piano, dall\'esperienza più che dai libri.'],'Saturno in nona cerca una verità che regga. La tua saggezza è guadagnata.'],
 [['Hai capito presto di voler costruire qualcosa che duri.','La tua carriera è cresciuta piano, passo dopo passo, ma su basi solide.','Gli altri ti considerano affidabile e ti affidano responsabilità.','Senti il peso delle aspettative, soprattutto delle tue.','Il riconoscimento arriva spesso tardi, ma resta.'],'Saturno in decima è in domicilio. La tua pazienza diventa autorità.'],
 [['Hai pochi amici, ma sono con te da anni.','In un gruppo ti senti più a tuo agio quando hai un ruolo preciso.','Spesso ti prendi l\'incarico di organizzare amici o associazioni.','I tuoi obiettivi sono concreti, e li pianifichi nei dettagli.','A volte, in un gruppo, hai avuto la sensazione di essere fuori posto.'],'Saturno in undicesima è in domicilio. Le amicizie fedeli sono il tuo terreno solido.'],
 [['Hai bisogno di solitudine, e sai usarla bene.','Porti preoccupazioni che non condividi con nessuno.','Lavori meglio dietro le quinte, con pazienza e metodo.','Le vecchie paure tornano nei momenti di quiete, e hai imparato ad affrontarle.','Una disciplina spirituale o interiore ti dà una struttura che regge.'],'Saturno in dodicesima è nella sua gioia. Nella solitudine trovi la tua solidità.']
]};

SB.urano = {
en:[
 [['People notice something different about you, even when you try to blend in.','You change your look, your plans or your mind more often than most.','Being told what to do triggers your need to do the opposite.','You make quick, unexpected decisions that surprise even you.','Your nerves react fast; pay attention to rest when life speeds up.'],'Uranus moves slowly through the signs, but in the 1st it becomes personal. Your freedom shows.'],
 [['Your income has had sudden ups and downs over the years.','You earn best in unusual ways, often with technology or independent work.','Possessions matter less to you than the freedom to move.','You have changed your idea of security more than once.','Fixed salaries and rigid budgets make you feel caged.'],'Uranus in the 2nd is in its fall. Security comes from adapting, not from holding on.'],
 [['Your mind jumps from one idea to the next at high speed.','You learn best on your own, outside the usual school methods.','In your family there has always been one unusual sibling or cousin, perhaps you.','You change neighbourhood, phone or habits more often than people expect.','You say surprising things that make people stop and think.'],'Uranus in the 3rd thinks in flashes. Write ideas down before they fly away.'],
 [['As a child you moved house more often than most people.','Your family was unusual in some way, or changed suddenly.','You need a home where you can be yourself, without imposed rules.','In your family you have often played the role of the black sheep.','Your life changes direction suddenly, often starting from home.'],'Uranus in the 4th shakes the roots. Your home can be your own invention.'],
 [['You fall in love suddenly, and fall out of it just as quickly.','You are attracted to people who are unusual or unconventional.','Your creativity is original and does not follow trends.','Children, or creative projects, arrived in unexpected ways.','You get bored in relationships that become too predictable.'],'Uranus in the 5th is in detriment. Passion needs freedom, and some constancy too.'],
 [['You hate rigid timetables and need flexibility in your work.','You find new, faster ways to handle routine tasks.','You have changed jobs or ways of working more than once.','Colleagues see you as the one who brings in new ideas.','Pay attention to nervous tension, which builds up when your routine is chaotic.'],'Uranus in the 6th reinvents daily life. Find a rhythm that leaves room for change.'],
 [['You need a partner who gives you space and does not try to hold you.','Your relationships tend to begin or end suddenly, with little warning.','You are attracted to original, independent people, or people from another world.','Traditional ideas about couples do not fit you.','In a relationship you value friendship as much as passion.'],'Uranus in the 7th wants a free bond. Space is your proof of love.'],
 [['You go through sudden changes that transform you deeply.','Esoteric studies, astrology and what science cannot yet explain intrigue you.','Shared money and inheritances have brought surprises into your life.','You get through crises thanks to sudden flashes of insight.','For you intimacy needs freedom, and possessiveness pushes you away.'],'Uranus in the 8th is exalted. Sudden turns become awakenings.'],
 [['Your beliefs have changed radically at least once.','You are drawn to unusual paths of study or alternative philosophies.','A trip or a meeting abroad suddenly changed your way of thinking.','You question any authority that cannot explain itself.','You love ideas that are ahead of their time.'],'Uranus in the 9th seeks truth off the usual routes. Your vision is original.'],
 [['Your career has taken unexpected turns, sometimes all at once.','You do not like bosses and prefer to work independently.','People know you for your own personal way of doing things.','A traditional career path feels too narrow for you.','Technology, innovation or reform attract you in your work.'],'Uranus in the 10th changes the direction of your path. Your originality is your role.'],
 [['Your friends are unusual, varied and often very different from you.','You are drawn to groups that want to change something.','Important people enter your life suddenly, and some leave just as suddenly.','Your plans for the future change often, but the direction stays.','Among people who think freely you truly feel at home.'],'Uranus in the 11th is in its own domicile. Your circle is your laboratory.'],
 [['Your intuitions arrive like flashes of lightning, without any warning.','You have an inner rebellious side that few people see.','You need moments of solitude to calm a restless mind.','Your most original solutions come to you in dreams or in silence.','At times you feel restless without quite knowing why.'],'Uranus in the 12th awakens you from within. Silence is where your insight sparks.']
],
it:[
 [['Gli altri notano qualcosa di diverso in te, anche quando cerchi di confonderti.','Cambi look, piani o idea più spesso della maggior parte delle persone.','Sentirti dire cosa fare risveglia il bisogno di fare il contrario.','Prendi decisioni rapide e inattese che sorprendono anche te.','I tuoi nervi reagiscono in fretta: fai attenzione al riposo quando la vita accelera.'],'Urano attraversa i segni lentamente, ma in prima diventa personale. La tua libertà si vede.'],
 [['Le tue entrate hanno avuto alti e bassi improvvisi nel corso degli anni.','Guadagni meglio in modi insoliti, spesso con la tecnologia o il lavoro autonomo.','I beni contano meno per te della libertà di muoverti.','Hai cambiato più di una volta la tua idea di sicurezza.','Stipendi fissi e bilanci rigidi ti fanno sentire in gabbia.'],'Urano in seconda è in caduta. La sicurezza nasce dall\'adattarsi, non dal trattenere.'],
 [['La tua mente salta da un\'idea all\'altra a grande velocità.','Impari meglio da te, fuori dagli schemi della scuola.','In famiglia, tra fratelli e cugini, c\'è sempre stata una figura fuori dal comune, forse tu.','Cambi quartiere, telefono o abitudini più spesso di quanto gli altri si aspettino.','Dici cose sorprendenti che fanno fermare e riflettere.'],'Urano in terza pensa per lampi. Annota le idee prima che volino via.'],
 [['Nell\'infanzia hai cambiato casa più spesso della maggior parte delle persone.','La tua famiglia era insolita, o è cambiata all\'improvviso.','Hai bisogno di una casa in cui essere te, senza regole imposte.','In famiglia hai avuto spesso il ruolo della pecora nera.','La tua vita cambia direzione all\'improvviso, spesso partendo dalla casa.'],'Urano in quarta scuote le radici. La tua casa può essere una tua invenzione.'],
 [['Ti innamori all\'improvviso, e con la stessa rapidità ti disinnamori.','Ti attraggono persone insolite o anticonvenzionali.','La tua creatività è originale e non segue le mode.','Figli o progetti creativi sono arrivati in modi inattesi.','Ti annoi nelle relazioni che diventano troppo prevedibili.'],'Urano in quinta è in esilio. La passione ha bisogno di libertà, e anche di costanza.'],
 [['Odi gli orari rigidi e hai bisogno di flessibilità nel lavoro.','Trovi modi nuovi e più rapidi per sbrigare i compiti di routine.','Hai cambiato lavoro o modo di lavorare più di una volta.','I colleghi vedono in te chi porta idee nuove.','Fai attenzione alla tensione nervosa, che cresce quando la routine è caotica.'],'Urano in sesta reinventa il quotidiano. Trova un ritmo che lasci spazio al cambiamento.'],
 [['Hai bisogno di un partner che ti lasci spazio e non cerchi di trattenerti.','Le tue relazioni tendono a iniziare o finire all\'improvviso, quasi senza preavviso.','Ti attraggono persone originali, indipendenti o di un altro mondo.','Le idee tradizionali di coppia non ti appartengono.','In una relazione dai all\'amicizia lo stesso valore della passione.'],'Urano in settima vuole un legame libero. Lo spazio è la tua prova d\'amore.'],
 [['Attraversi cambiamenti improvvisi che ti trasformano a fondo.','Ti incuriosiscono l\'esoterismo, l\'astrologia e ciò che la scienza non spiega ancora.','Soldi condivisi ed eredità hanno portato sorprese nella tua vita.','Superi le crisi grazie a lampi improvvisi di intuizione.','Per te l\'intimità ha bisogno di libertà, e il possesso ti allontana.'],'Urano in ottava è in esaltazione. Le svolte improvvise diventano risvegli.'],
 [['Le tue convinzioni sono cambiate radicalmente almeno una volta.','Ti attraggono percorsi di studio insoliti o filosofie alternative.','Un viaggio o un incontro all\'estero ha cambiato di colpo il tuo modo di pensare.','Metti in discussione ogni autorità che non sa spiegarsi.','Ami le idee in anticipo sui tempi.'],'Urano in nona cerca la verità fuori dalle strade solite. La tua visione è originale.'],
 [['La tua carriera ha preso svolte inattese, a volte tutte insieme.','Non ami i capi e preferisci lavorare in autonomia.','Ti conoscono per il tuo modo personale di fare le cose.','Una carriera tradizionale ti sta stretta.','Tecnologia, innovazione o riforme ti attirano nel lavoro.'],'Urano in decima cambia la direzione del tuo percorso. La tua originalità è il tuo ruolo.'],
 [['I tuoi amici sono insoliti, vari e spesso molto diversi da te.','Ti attirano i gruppi che vogliono cambiare qualcosa.','Persone importanti entrano all\'improvviso nella tua vita, e alcune escono allo stesso modo.','I tuoi progetti per il futuro cambiano spesso, ma la direzione resta.','Tra persone che pensano liberamente ti senti davvero a casa.'],'Urano in undicesima è in domicilio. La tua cerchia è il tuo laboratorio.'],
 [['Le intuizioni ti arrivano come lampi, senza alcun preavviso.','Hai un lato ribelle interiore che pochi vedono.','Hai bisogno di momenti di solitudine per calmare una mente irrequieta.','Le soluzioni più originali ti arrivano nei sogni o nel silenzio.','A volte senti un\'inquietudine senza saperne bene il motivo.'],'Urano in dodicesima ti risveglia da dentro. Il silenzio è dove scocca la tua intuizione.']
]};

SB.nettuno = {
en:[
 [['People see in you whatever they want to see, and you let them.','You absorb the mood of a room as soon as you walk in.','Your face and style seem to change with your state of mind.','Saying no is hard for you, because you feel what others feel.','There is something dreamy or elusive about you that people remember.'],'Neptune is generational by sign, but in the 1st it colours your presence. Your sensitivity is a gift; give it edges.'],
 [['Money slips through your fingers without you quite knowing how.','You give generously, sometimes more than you can afford.','Beauty, music and meaning matter more to you than objects.','Paperwork and numbers bore you, and you tend to put them off.','You would rather earn through creative or caring work than through dull routine.'],'Neptune in the 2nd dreams of a worth beyond money. Keep your accounts clear and your ideals high.'],
 [['You think in images, moods and impressions rather than in lists.','You forget names and dates but remember how a conversation made you feel.','You write poems, lyrics or diaries, even if you never show them.','Misunderstandings happen to you more than to others; repeat what matters.','You can sense what someone is about to say before they say it.'],'Neptune in the 3rd speaks the language of images. Check the facts, trust the feeling.'],
 [['Your home is a refuge where you can dream undisturbed.','Your childhood is wrapped in some mystery or an untold story.','A parent was sensitive, idealised or hard to reach.','You dream of a house near water or far from the noise.','You sense the atmosphere of a house as soon as you enter.'],'Neptune in the 4th is exalted. Your roots run deep and quiet.'],
 [['You fall in love with an ideal, sometimes more than with the person.','Music, theatre, film or painting move you deeply.','Your creativity flows best when you do not force it.','You have a gentle, almost magical way with children.','A disappointment in love taught you to see more clearly.'],'Neptune in the 5th loves through dreams. Keep the poetry and open your eyes.'],
 [['You prefer work that helps, heals or inspires others.','Messy routines make you lose track of time and tasks.','You absorb your colleagues\' tension without noticing it.','Pay attention to what you take in, because your body is sensitive to excess.','You give more than is asked of you, and sometimes nobody notices.'],'Neptune in the 6th is in detriment. Serve with your heart, and protect your energy.'],
 [['You see the best in your partner, sometimes more than is really there.','You are drawn to artistic, sensitive or wounded people.','In relationships you tend to sacrifice your own needs without saying so.','Your ideal relationship is a spiritual union rather than a contract.','You have learned to tell love apart from the urge to rescue someone.'],'Neptune in the 7th idealises the other. Love clearly, not blindly.'],
 [['You feel other people\'s emotions as if they were your own.','Mysticism, dreams and everything beyond the visible draw you in.','Shared money or inheritances have been confused or unclear in your story.','You need deep emotional fusion, and you fear losing yourself in it.','Every crisis transforms you and often leaves you a spiritual insight.'],'Neptune in the 8th dissolves boundaries. Let go, and still keep your shape.'],
 [['You keep searching: faiths, mysteries and spiritual paths attract you.','Faraway places, especially by the sea, call to you.','You idealised a teacher or a belief, and later saw its limits.','You learn more through intuition than through textbooks.','Your vision of life is wide and compassionate.'],'Neptune in the 9th searches for the infinite. Keep your faith and your discernment.'],
 [['Your career path has been uncertain, changing or hard to define.','You are drawn to art, care or spiritual work.','People project images onto you that do not quite match who you are.','You want your work to have meaning, not only success.','You once had a career dream that seemed unrealistic to others.'],'Neptune in the 10th is in its fall. Give your vision a concrete form.'],
 [['Your friends include artists, dreamers and sensitive souls.','You idealise groups and causes, and sometimes they disappoint you.','You help your friends without keeping count of what you give.','Your hopes for the future are wide and generous, at times vague.','You feel a strong bond with communities that share an ideal.'],'Neptune in the 11th dreams together with others. Choose your circle with open eyes.'],
 [['You need solitude, silence and time near water or in nature.','Your dreams are vivid, and they often carry a meaning for you.','You feel the pain of others very strongly, even of strangers.','Meditation, prayer or art help you feel whole again.','At times you escape when reality becomes too heavy.'],'Neptune in the 12th is in its own domicile. Your inner world is vast; build a bridge back to daily life.']
],
it:[
 [['Gli altri vedono in te ciò che vogliono vedere, e tu glielo lasci fare.','Assorbi l\'umore di una stanza appena entri.','Il tuo volto e il tuo stile sembrano cambiare con il tuo stato d\'animo.','Ti costa dire di no, perché senti ciò che sentono gli altri.','C\'è qualcosa di sognante o sfuggente in te che la gente ricorda.'],'Nettuno è generazionale per segno, ma in prima colora la tua presenza. La sensibilità è un dono: dalle dei contorni.'],
 [['Il denaro ti scivola tra le dita senza che tu sappia bene come.','Dai con generosità, a volte più di quanto puoi permetterti.','Bellezza, musica e senso contano per te più degli oggetti.','Burocrazia e numeri ti annoiano, e tendi a rimandarli.','Preferisci guadagnare con un lavoro creativo o di cura che con una routine arida.'],'Nettuno in seconda sogna un valore oltre il denaro. Tieni chiari i conti e alti gli ideali.'],
 [['Pensi per immagini, atmosfere e impressioni più che per elenchi.','Dimentichi nomi e date, ma ricordi come ti ha fatto sentire una conversazione.','Scrivi poesie, testi o diari, anche se non li mostri mai.','Ti capitano più malintesi che agli altri: ripeti ciò che conta.','Senti cosa sta per dire qualcuno prima che lo dica.'],'Nettuno in terza parla la lingua delle immagini. Verifica i fatti, fidati della sensazione.'],
 [['La tua casa è un rifugio dove sognare senza disturbi.','La tua infanzia è avvolta da un mistero o da una storia mai detta.','Un genitore era sensibile, idealizzato o difficile da raggiungere.','Sogni una casa vicino all\'acqua o lontana dal rumore.','Senti l\'atmosfera di una casa appena entri.'],'Nettuno in quarta è in esaltazione. Le tue radici sono profonde e silenziose.'],
 [['Ti innamori di un ideale, a volte più che della persona.','Musica, teatro, cinema o pittura ti commuovono profondamente.','La tua creatività scorre meglio quando non la forzi.','Con i bambini hai un modo dolce, quasi magico.','Una delusione d\'amore ti ha insegnato a vedere con più chiarezza.'],'Nettuno in quinta ama sognando. Tieni la poesia e apri gli occhi.'],
 [['Preferisci lavori che aiutano, curano o ispirano gli altri.','Le routine disordinate ti fanno perdere il filo del tempo e dei compiti.','Assorbi la tensione dei colleghi senza accorgertene.','Fai attenzione a ciò che assumi: il tuo corpo è sensibile agli eccessi.','Dai più di quanto ti viene chiesto, e a volte nessuno se ne accorge.'],'Nettuno in sesta è in esilio. Servi con il cuore e proteggi la tua energia.'],
 [['Vedi il meglio nel partner, a volte più di quanto ci sia davvero.','Ti attraggono persone artistiche, sensibili o ferite.','Nelle relazioni tendi a sacrificare i tuoi bisogni senza dirlo.','La tua relazione ideale è un\'unione spirituale più che un contratto.','Hai imparato a distinguere l\'amore dal bisogno di salvare qualcuno.'],'Nettuno in settima idealizza l\'altro. Ama con chiarezza, non alla cieca.'],
 [['Senti le emozioni degli altri come se fossero tue.','Ti attirano la mistica, i sogni e tutto ciò che va oltre il visibile.','Soldi condivisi o eredità sono stati confusi o poco chiari nella tua storia.','Hai bisogno di una fusione emotiva profonda, e temi di perderti.','Ogni crisi ti trasforma e spesso ti lascia un\'intuizione spirituale.'],'Nettuno in ottava dissolve i confini. Lasciati andare, ma conserva la tua forma.'],
 [['Cerchi di continuo: fedi, misteri e percorsi spirituali ti attraggono.','I luoghi lontani, soprattutto sul mare, ti chiamano.','Hai idealizzato un maestro o una credenza, e poi ne hai visto i limiti.','Impari più con l\'intuizione che con i manuali.','La tua visione della vita è ampia e compassionevole.'],'Nettuno in nona cerca l\'infinito. Conserva la fede e il discernimento.'],
 [['Il tuo percorso professionale è stato incerto, mutevole o difficile da definire.','Ti attraggono l\'arte, la cura o il lavoro spirituale.','Gli altri proiettano su di te immagini che non ti somigliano del tutto.','Vuoi che il tuo lavoro abbia un senso, non solo successo.','Hai avuto un sogno professionale che agli altri sembrava irrealistico.'],'Nettuno in decima è in caduta. Dai alla tua visione una forma concreta.'],
 [['Tra i tuoi amici ci sono artisti, sognatori e anime sensibili.','Idealizzi gruppi e cause, e a volte ti deludono.','Aiuti gli amici senza fare i conti di quello che dai.','Le tue speranze per il futuro sono ampie e generose, a volte vaghe.','Senti un legame forte con le comunità che condividono un ideale.'],'Nettuno in undicesima sogna insieme agli altri. Scegli la tua cerchia a occhi aperti.'],
 [['Hai bisogno di solitudine, silenzio e tempo vicino all\'acqua o nella natura.','I tuoi sogni sono vividi, e spesso hanno un significato per te.','Senti con forza il dolore degli altri, anche degli sconosciuti.','Meditazione, preghiera o arte ti ricompongono.','A volte fuggi quando la realtà diventa troppo pesante.'],'Nettuno in dodicesima è in domicilio. Il tuo mondo interiore è vasto: costruisci un ponte verso il quotidiano.']
]};

SB.plutone = {
en:[
 [['People sense your intensity, even when you say very little.','You reveal yourself slowly and observe others carefully first.','At least once in your life you have completely changed your skin.','You notice at once when someone tries to control you, and you resist.','Your presence can calm a room or make it tense.'],'Pluto is generational by sign, but in the 1st it becomes your presence. Use your intensity to protect, not to control.'],
 [['You want control over your own resources and hate depending on others.','Your relationship with money has gone through deep crises and rebirths.','You can lose everything and rebuild from scratch.','Objects carry an emotional weight for you that goes beyond their value.','About what you consider yours, you do not give an inch.'],'Pluto in the 2nd is in detriment. Your true resource is your ability to rebuild.'],
 [['Your words can be piercing, sometimes more than you intend.','You dig, research and want to get to the bottom of things.','Something important was left unsaid between you and a brother or sister.','You keep secrets well and notice what others hide.','A single conversation has changed the course of your life.'],'Pluto in the 3rd thinks in depth. Your questions can heal or wound.'],
 [['Your family had secrets, tensions or a strong figure who dominated.','Home is the place where your deepest transformations happen.','You have had to free yourself from a family pattern.','You protect your private life fiercely, even from the people closest to you.','A move or a change of home marked a turning point in your life.'],'Pluto in the 4th transforms the roots. Breaking a pattern is your inheritance.'],
 [['You love with total intensity, never halfway and never lightly.','Jealousy in love is something you have had to learn to manage.','Your creativity comes from deep places and can be powerful.','Children, or creative projects, have transformed your life.','You are drawn to passions that others find excessive.'],'Pluto in the 5th is exalted. Your passion is power; let it create.'],
 [['You throw yourself into work with an almost obsessive focus.','Wherever you work, you change the way things are done.','Power struggles at work have taught you a lot about yourself.','Pay attention to the stress you hold inside; it tends to show in the body.','After a crisis you know how to rebuild a routine from zero.'],'Pluto in the 6th transforms daily life. Small changes, repeated, become a rebirth.'],
 [['Your relationships are intense and change you deeply.','You attract strong partners, and power struggles can arise.','Trust is everything for you, and a betrayal is hard to forgive.','One relationship in particular has transformed your life completely.','You see the hidden motives of others very clearly.'],'Pluto in the 7th meets power in the other. Seek depth without control.'],
 [['You are not afraid of the darker sides of life.','Psychology, research or esoteric studies attract you strongly.','You have been through deep crises and found a way to be reborn.','Shared resources or inheritances have weighed heavily in your story.','You read people\'s secrets easily, and you keep yours well.'],'Pluto in the 8th is in its own domicile. Rebirth is your strength.'],
 [['Your beliefs have been through a radical crisis and a rebirth.','You seek the truth all the way down, without compromise.','A journey or an encounter with another culture changed you deeply.','An idea can take hold of you completely before you learn to question it.','Philosophy, psychology or esoteric studies attract you deeply.'],'Pluto in the 9th searches for the truth beneath truths. As you dig deeper, keep listening.'],
 [['You want real influence, not just a visible role.','Your career has gone through radical endings and fresh beginnings.','At work you attract or confront powerful figures.','People sense your determination even when you stay silent.','You know how to rise again after a professional fall.'],'Pluto in the 10th seeks power in the world. Use it to transform, not to dominate.'],
 [['Your friendships are few, but intense and able to transform you.','You have lost or ended friendships that no longer reflected who you were.','You are drawn to groups that want profound change.','In groups you often end up leading from behind the scenes.','Your hopes for the future have changed radically at least once.'],'Pluto in the 11th is in its fall. Choose groups that let you stay yourself.'],
 [['You carry a deep inner world that few people know.','Old fears or family secrets resurface in quiet moments.','You have an instinct for what hides behind appearances.','You transform yourself through solitude, therapy or inner work.','At times you feel the pull of forces you cannot name.'],'Pluto in the 12th transforms from within. What you bring to light loses its power over you.']
],
it:[
 [['Gli altri percepiscono la tua intensità, anche quando parli poco.','Ti riveli piano, e prima osservi gli altri con attenzione.','Almeno una volta nella vita hai cambiato completamente pelle.','Ti accorgi subito quando qualcuno cerca di controllarti, e non lo accetti.','La tua presenza può calmare una stanza o renderla tesa.'],'Plutone è generazionale per segno, ma in prima diventa la tua presenza. Usa l\'intensità per proteggere, non per controllare.'],
 [['Vuoi il controllo delle tue risorse e odi dipendere dagli altri.','Il tuo rapporto con il denaro ha attraversato crisi profonde e rinascite.','Puoi perdere tutto e ricostruire da zero.','Gli oggetti hanno per te un peso emotivo che va oltre il loro valore.','Su ciò che consideri tuo non molli di un passo.'],'Plutone in seconda è in esilio. La tua vera risorsa è la capacità di ricostruire.'],
 [['Le tue parole possono essere penetranti, a volte più di quanto vorresti.','Scavi, ricerchi e vuoi arrivare in fondo alle cose.','Tra te e un fratello o una sorella è rimasto qualcosa di non detto.','Custodisci bene i segreti e noti ciò che gli altri nascondono.','Una sola conversazione ha cambiato il corso della tua vita.'],'Plutone in terza pensa in profondità. Le tue domande possono guarire o ferire.'],
 [['La tua famiglia aveva segreti, tensioni o una figura forte che dominava.','La casa è il luogo delle tue trasformazioni più profonde.','Hai dovuto liberarti da uno schema familiare.','Proteggi la tua vita privata con forza, anche dalle persone più vicine.','Un trasloco o un cambio di casa ha segnato una svolta nella tua vita.'],'Plutone in quarta trasforma le radici. Spezzare uno schema è la tua eredità.'],
 [['Ami con un\'intensità totale, mai a metà e mai alla leggera.','La gelosia in amore è qualcosa che hai dovuto imparare a gestire.','La tua creatività nasce da luoghi profondi e può essere potente.','Figli o progetti creativi hanno trasformato la tua vita.','Ti attraggono passioni che altri trovano eccessive.'],'Plutone in quinta è in esaltazione. La tua passione è potere: lascia che crei.'],
 [['Ti butti nel lavoro con una concentrazione quasi ossessiva.','Ovunque lavori, cambi il modo in cui si fanno le cose.','Le lotte di potere sul lavoro ti hanno insegnato molto su di te.','Fai attenzione allo stress che trattieni: tende a farsi sentire nel corpo.','Dopo una crisi sai ricostruire una routine da zero.'],'Plutone in sesta trasforma il quotidiano. Piccoli cambiamenti, ripetuti, diventano una rinascita.'],
 [['Le tue relazioni sono intense e ti cambiano a fondo.','Attrai partner forti, e possono nascere lotte di potere.','Per te la fiducia è tutto, e un tradimento è difficile da perdonare.','Una relazione in particolare ha trasformato completamente la tua vita.','Vedi con grande chiarezza le motivazioni nascoste degli altri.'],'Plutone in settima incontra il potere nell\'altro. Cerca la profondità senza controllo.'],
 [['Non hai paura dei lati più oscuri della vita.','Psicologia, ricerca o studi esoterici ti attirano con forza.','Hai attraversato crisi profonde e hai saputo rinascere.','Risorse condivise o eredità hanno pesato molto nella tua storia.','Leggi facilmente i segreti delle persone, e custodisci bene i tuoi.'],'Plutone in ottava è in domicilio. La rinascita è la tua forza.'],
 [['Le tue convinzioni hanno attraversato una crisi radicale e una rinascita.','Cerchi la verità fino in fondo, senza compromessi.','Un viaggio o l\'incontro con un\'altra cultura ti ha cambiato a fondo.','Un\'idea può prenderti del tutto, prima che impari a metterla in discussione.','Filosofia, psicologia o studi esoterici ti attirano profondamente.'],'Plutone in nona cerca la verità sotto le verità. Mentre scendi in profondità, resta in ascolto.'],
 [['Vuoi un\'influenza reale, non solo un ruolo visibile.','La tua carriera ha attraversato fini radicali e nuovi inizi.','Sul lavoro attrai o affronti figure potenti.','Gli altri sentono la tua determinazione anche quando taci.','Sai rialzarti dopo una caduta professionale.'],'Plutone in decima cerca potere nel mondo. Usalo per trasformare, non per dominare.'],
 [['Le tue amicizie sono poche, ma intense e capaci di trasformarti.','Hai perso o chiuso amicizie che non rispecchiavano più chi eri.','Ti attirano i gruppi che vogliono un cambiamento profondo.','Nei gruppi finisci spesso per guidare da dietro le quinte.','Le tue speranze per il futuro sono cambiate radicalmente almeno una volta.'],'Plutone in undicesima è in caduta. Scegli gruppi che ti lascino essere te.'],
 [['Porti dentro un mondo interiore profondo che pochi conoscono.','Vecchie paure o segreti di famiglia riemergono nei momenti di quiete.','Hai un istinto per ciò che si nasconde dietro le apparenze.','Ti trasformi attraverso la solitudine, la terapia o il lavoro interiore.','A volte senti l\'influenza di forze che non sai nominare.'],'Plutone in dodicesima trasforma da dentro. Ciò che porti alla luce perde potere su di te.']
]};

SB_UI.en.tpl.marte = 'If you have Mars in the {n} house, you probably:';
SB_UI.en.tpl.giove = 'If you have Jupiter in the {n} house, you probably:';
SB_UI.en.tpl.saturno = 'If you have Saturn in the {n} house, you probably:';
SB_UI.en.tpl.urano = 'If you have Uranus in the {n} house, you probably:';
SB_UI.en.tpl.nettuno = 'If you have Neptune in the {n} house, you probably:';
SB_UI.en.tpl.plutone = 'If you have Pluto in the {n} house, you probably:';
SB_UI.en.cta.marte = 'Don\'t know which house your Mars is in? The natal chart is free.';
SB_UI.en.cta.giove = 'Don\'t know which house your Jupiter is in? The natal chart is free.';
SB_UI.en.cta.saturno = 'Don\'t know which house your Saturn is in? The natal chart is free.';
SB_UI.en.cta.urano = 'Don\'t know which house your Uranus is in? The natal chart is free.';
SB_UI.en.cta.nettuno = 'Don\'t know which house your Neptune is in? The natal chart is free.';
SB_UI.en.cta.plutone = 'Don\'t know which house your Pluto is in? The natal chart is free.';
SB_UI.it.tpl.marte = 'Se hai Marte in {n} casa, probabilmente:';
SB_UI.it.tpl.giove = 'Se hai Giove in {n} casa, probabilmente:';
SB_UI.it.tpl.saturno = 'Se hai Saturno in {n} casa, probabilmente:';
SB_UI.it.tpl.urano = 'Se hai Urano in {n} casa, probabilmente:';
SB_UI.it.tpl.nettuno = 'Se hai Nettuno in {n} casa, probabilmente:';
SB_UI.it.tpl.plutone = 'Se hai Plutone in {n} casa, probabilmente:';
SB_UI.it.cta.marte = 'Non sai in che casa hai Marte? Il tema natale è gratuito.';
SB_UI.it.cta.giove = 'Non sai in che casa hai Giove? Il tema natale è gratuito.';
SB_UI.it.cta.saturno = 'Non sai in che casa hai Saturno? Il tema natale è gratuito.';
SB_UI.it.cta.urano = 'Non sai in che casa hai Urano? Il tema natale è gratuito.';
SB_UI.it.cta.nettuno = 'Non sai in che casa hai Nettuno? Il tema natale è gratuito.';
SB_UI.it.cta.plutone = 'Non sai in che casa hai Plutone? Il tema natale è gratuito.';
