# Poster «Retrogrado nei 12 segni» e «Aspetti» — italiano.
# Regole: seconda persona singolare, mai prima persona plurale, niente trading/mercati.
import json
S = {
'aries': ("Ariete", "dell'Ariete", [
  "Le parole sparate troppo in fretta: ripetile, più piano.",
  "Il modo in cui insegui ciò che desideri: lascia che l'attrazione si avvicini da sola.",
  "Le liti iniziate d'istinto: scegli quali contano ancora.",
  "La fiducia nei salti audaci: verifica quali ti hanno fatto crescere davvero.",
  "La pazienza che hai saltato: ricostruisci il coraggio su basi più solide.",
  "La voglia di liberarti: chiediti per cosa ti stai liberando.",
  "L'immagine eroica che hai di te: lascia che si ammorbidisca nella verità.",
  "Dove la volontà è diventata forza: riprendi potere senza spingere."],
  "L'Ariete corre avanti; il moto retrogrado gli fa voltare lo sguardo.",
  ["Nel racconto greco, un ariete d'oro volò in soccorso.",
   "Nefele lo mandò a salvare Frisso ed Elle da Ino.",
   "Elle scivolò in mare, da allora chiamato Ellesponto.",
   "Frisso giunse in Colchide e offrì l'ariete a Zeus.",
   "Il suo vello, appeso in un bosco sorvegliato, fu il Vello d'oro.",
   "L'ariete salì tra le stelle, primo segno della primavera."],
  "Ciò che hai affrettato può chiedere di ricominciare."),
'taurus': ("Toro", "del Toro", [
  "Le opinioni che hai fissato da tempo: riaprile con curiosità nuova.",
  "Ciò che per te ha davvero valore: lascia le comodità che non senti più tue.",
  "Dove la testardaggine sembrava forza: muoviti con calma, ma muoviti.",
  "La tua idea di abbondanza: nota quanto contiene già il «basta».",
  "Ciò a cui ti aggrappi per paura: tieni solo ciò che dura.",
  "Le abitudini che chiami sicurezza: lascia entrare un piccolo cambiamento.",
  "I sogni che hai messo nelle cose: cerca la bellezza che non va posseduta.",
  "Ciò che possiedi, e ciò che in silenzio possiede te: allenta la presa."],
  "Il Toro costruisce piano; il moto retrogrado cura le fondamenta.",
  ["Nel racconto greco, Zeus si fece toro bianco e splendente.",
   "Europa, che coglieva fiori sulla riva, gli salì in groppa.",
   "Lui nuotò attraverso il mare e la portò fino a Creta.",
   "Suo figlio Minosse divenne il re leggendario dell'isola.",
   "L'immagine del toro fu innalzata nel cielo notturno.",
   "Le Iadi ne segnano il muso, le Pleiadi la spalla."],
  "Ciò che conservi può chiedere di essere scelto di nuovo."),
'gemini': ("Gemelli", "dei Gemelli", [
  "I messaggi letti a metà: tornaci con piena attenzione.",
  "Come flirti con idee e persone: nota quali conversazioni ti uniscono davvero.",
  "Le discussioni vinte con l'astuzia: chiediti se valeva la pena vincerle.",
  "Tutto ciò che volevi imparare insieme: scegli un filo e seguilo.",
  "I progetti sparsi: dai a un'idea la struttura che merita.",
  "La mente irrequieta: lascia posare l'intuizione prima di parlare.",
  "Le storie che ti racconti: separa ciò che hai sentito da ciò che è vero.",
  "Parole con un peso nascosto: di' ciò che intendi davvero."],
  "I Gemelli fanno domande; il moto retrogrado le fa due volte.",
  ["Nel racconto greco, Castore e Polluce erano i gemelli di Leda.",
   "Castore era mortale; Polluce, figlio di Zeus, immortale.",
   "Quando Castore cadde, Polluce non volle vivere senza di lui.",
   "Zeus diede loro un destino comune, tra Olimpo e Ade.",
   "Posti fianco a fianco nel cielo, guidano i marinai."],
  "Ciò che hai detto può chiedere di essere ascoltato di nuovo."),
'cancer': ("Cancro", "del Cancro", [
  "Vecchi discorsi di famiglia: riascolta ciò che volevano dire davvero.",
  "Come ti prendi cura degli altri: lascia che si prendano cura anche di te.",
  "Il modo in cui difendi i tuoi: proteggi senza chiudere la porta.",
  "Cosa significa casa per te oggi: allarga il cerchio che chiami famiglia.",
  "I muri costruiti per sentirti al sicuro: verifica quali ti servono ancora.",
  "Abitudini ereditate in casa: tieni il calore, cambia lo schema.",
  "La nostalgia che colora i ricordi: onora il passato senza viverci.",
  "Radici profonde e vecchie lealtà: lascia ciò che non era tuo da portare."],
  "Il Cancro ricorda; il moto retrogrado lo aiuta a ricordare con gentilezza.",
  ["Nel racconto greco, Era mandò un granchio contro Eracle.",
   "L'eroe combatteva l'Idra nelle paludi di Lerna.",
   "Il granchio gli pizzicò il piede, e lui lo schiacciò.",
   "Era premiò la sua fedeltà con un posto tra le stelle.",
   "Le sue stelle deboli custodiscono l'ammasso del Presepe."],
  "Ciò che hai protetto può chiedere di essere sentito di nuovo."),
'leo': ("Leone", "del Leone", [
  "Come racconti la tua storia: lascia entrare altre voci.",
  "Romanticismo e gioco: ama per la gioia, non per l'applauso.",
  "L'orgoglio diventato sfida: guida con il calore, non con la forza.",
  "Generosità e grandi gesti: dona dove arriva davvero.",
  "Il bisogno di essere visto: costruisci una fiducia che regga al buio.",
  "La tua firma creativa: lascia che sorprenda anche te, ancora una volta.",
  "Il ruolo che reciti per piacere: trova chi sei sotto il costume.",
  "Dove l'orgoglio difende una vecchia ferita: guida col cuore, non con l'ego."],
  "Il Leone brilla fuori; il moto retrogrado volge la luce dentro.",
  ["Nel racconto greco, un leone terrorizzava la valle di Nemea.",
   "Nessuna arma poteva trafiggere la sua pelle dorata.",
   "Eracle lo chiuse nella sua grotta e lo strangolò.",
   "Da allora ne indossò la pelle come mantello e armatura.",
   "Zeus pose il leone nel cielo, con Regolo nel cuore."],
  "Ciò che hai mostrato può chiedere di essere sentito di nuovo."),
'virgo': ("Vergine", "della Vergine", [
  "I dettagli che correggevi negli altri: rivolgi quella cura a te.",
  "Come mostri amore servendo: lascia che la gratitudine vada nei due sensi.",
  "Il lavoro di ogni giorno: affina il metodo invece di spingere di più.",
  "I tuoi standard di miglioramento: lascia spazio al «va bene così».",
  "I doveri presi in silenzio: tieni quelli che contano davvero.",
  "Routine rigide: inventa un modo migliore per fare le cose di sempre.",
  "La perfezione che insegui: fidati che anche il lavoro imperfetto conta.",
  "Il bisogno di controllare ogni dettaglio: setaccia, e lascia andare il resto."],
  "La Vergine seleziona il raccolto; il moto retrogrado lo seleziona di nuovo.",
  ["Nel racconto greco è Astrea, la fanciulla della giustizia.",
   "Visse tra gli esseri umani durante l'età dell'oro.",
   "Quando divennero crudeli, fu l'ultima immortale ad andarsene.",
   "Salì nel cielo con in mano una spiga di grano.",
   "Quella spiga è Spica, la stella luminosa del raccolto."],
  "Ciò che hai perfezionato può chiedere di essere allentato."),
'libra': ("Bilancia", "della Bilancia", [
  "Accordi e promesse: rileggi i patti accettati per quieto vivere.",
  "Le tue relazioni: chiediti se il dare e l'avere sono ancora equi.",
  "Conflitti evitati per armonia: parla, con gentilezza ma con chiarezza.",
  "I tuoi ideali di giustizia: applicali anche a te.",
  "Impegni presi con gli altri: pesa quali sono equilibrati e veri.",
  "I ruoli che reciti nelle relazioni: lasciatevi spazio per cambiare.",
  "Il partner ideale che immaginavi: guarda la persona reale davanti a te.",
  "Il potere nascosto nella cortesia: riequilibra dove un lato pesa troppo."],
  "La Bilancia pesa; il moto retrogrado lascia che i piatti si fermino.",
  ["I primi astronomi greci vedevano qui le chele dello Scorpione.",
   "Le sue stelle più luminose portano ancora il nome delle due chele.",
   "I Romani lessero la figura come un paio di piatti.",
   "Nell'antichità il Sole passava qui vicino all'equinozio d'autunno.",
   "È l'unica figura dello zodiaco che è un oggetto, non un essere."],
  "Ciò che hai bilanciato può chiedere di essere ripesato."),
'scorpio': ("Scorpione", "dello Scorpione", [
  "Segreti custoditi e cose non dette: decidi cosa merita la luce.",
  "Intimità e fiducia: chiediti chi ha meritato la tua profondità, e chi no.",
  "Vecchi rancori silenziosi: volgi quell'intensità al rinnovamento.",
  "Ciò che condividi con gli altri: fa' crescere la fiducia dove è ricambiata.",
  "La paura di perdere: costruisci vicinanza sui confini, non sul controllo.",
  "Gelosia e sospetto: lascia che un'onestà improvvisa schiarisca l'aria.",
  "Il sogno di fonderti del tutto: ama a fondo restando te.",
  "Ciò che deve finire perché qualcosa cominci: lascia la vecchia pelle."],
  "Lo Scorpione scava a fondo; il moto retrogrado torna a ciò che è sepolto.",
  ["Nel racconto greco, Orione si vantava di poter uccidere ogni bestia.",
   "Gaia mandò uno scorpione, e il suo pungiglione abbatté il cacciatore.",
   "Entrambi furono posti nel cielo, ai lati opposti.",
   "Quando lo Scorpione sorge a est, Orione tramonta a ovest.",
   "Nel suo cuore arde la rossa Antares, «rivale di Ares»."],
  "Ciò che hai sepolto può chiedere di essere affrontato di nuovo."),
'sagittarius': ("Sagittario", "del Sagittario", [
  "Le affermazioni fatte con certezza: verifica i fatti ancora una volta.",
  "L'amore che vive di distanza e sogni: avvicinalo a casa.",
  "Le crociate per le tue idee: mira le frecce con più cura.",
  "La tua grande filosofia di vita: vedi se si adatta ancora all'esperienza.",
  "Promesse più grandi della tua portata: trasforma la visione in passi reali.",
  "Credenze ereditate: verifica quali verità hai scelto e quali hai preso in prestito.",
  "Maestri e guru idealizzati: lascia che ti guidi la tua saggezza.",
  "Convinzioni strette troppo forte: lascia che la tua verità evolva."],
  "Il Sagittario mira lontano; il moto retrogrado controlla la mira.",
  ["L'Arciere, spesso disegnato come centauro, mira allo Scorpione.",
   "In un racconto greco è Croto, cresciuto tra le Muse.",
   "Si dice inventò il tiro con l'arco; cavalcava bene quanto tirava.",
   "Le Muse chiesero a Zeus di onorarlo con un posto nel cielo.",
   "Verso il suo arco si trova il centro della Via Lattea."],
  "Ciò in cui hai creduto può chiedere di essere messo alla prova."),
'capricorn': ("Capricorno", "del Capricorno", [
  "Piani a lungo termine e impegni formali: rivedi la via prima di salire.",
  "L'amore rimandato per dovere: fai spazio alla tenerezza adesso.",
  "L'ambizione mossa solo dalla disciplina: sali a un ritmo sostenibile.",
  "La tua idea di successo: misurala col significato, non con lo status.",
  "Il rapporto con autorità e regole: tieni le strutture che ti sostengono.",
  "Tradizioni seguite per abitudine: rinnovale, o costruiscene di nuove.",
  "L'immagine di chi ce la fa: lascia che l'ambizione serva i tuoi veri sogni.",
  "Dove il controllo ha preso il posto della responsabilità: fonda l'autorità sull'integrità."],
  "Il Capricorno sale; il moto retrogrado controlla ogni appiglio.",
  ["La capra marina è più antica della Grecia: un pesce-capra babilonese.",
   "In Mesopotamia era legata a Ea, dio delle acque dolci.",
   "Nel racconto greco, Pan fuggì dal mostro Tifone.",
   "Si gettò nel fiume: la sua metà inferiore divenne pesce.",
   "Zeus pose quella fuga ingegnosa tra le stelle."],
  "Ciò che hai costruito può chiedere di essere riplasmato."),
'aquarius': ("Acquario", "dell'Acquario", [
  "Le idee condivise con i tuoi gruppi: riprendile con mente più fresca.",
  "Amicizie e famiglia scelta: nota quali legami sono ancora reciproci.",
  "Le cause per cui lotti: verifica che riflettano ancora i tuoi valori.",
  "Le speranze per il futuro: rinnova la visione con la saggezza di oggi.",
  "Il tuo ruolo nella comunità: contribuisci senza perdere la tua voce.",
  "Il ribelle dentro di te: chiediti se resisti per libertà o per abitudine.",
  "Sogni di utopia: trasforma gli ideali comuni in gesti che puoi fare davvero.",
  "Pressione del gruppo e potere collettivo: resta fedele a te restando in contatto."],
  "L'Acquario guarda avanti; il moto retrogrado gli fa guardare intorno.",
  ["Nel racconto greco è Ganimede, un giovane di Troia.",
   "L'aquila di Zeus lo portò sull'Olimpo.",
   "Lì divenne il coppiere degli dèi.",
   "Nel cielo versa acqua da un'urna verso sud.",
   "Il getto scorre verso il Pesce Australe e la luminosa Fomalhaut."],
  "Ciò che hai immaginato può chiedere di essere rinnovato."),
'pisces': ("Pesci", "dei Pesci", [
  "Pensieri rimasti a galla senza voce: dai alle intuizioni parole chiare e semplici.",
  "L'amore che ha sciolto i tuoi confini: offri compassione e tieni te stesso.",
  "Battaglie evitate ritirandoti: agisci con dolcezza, ma agisci.",
  "La tua fede e la tua generosità: dona senza svuotarti.",
  "Sogni senza forma: dai loro una struttura semplice e costante.",
  "Le abitudini spirituali: lascia che un'intuizione improvvisa risvegli la pratica.",
  "Illusioni in cui nuotavi volentieri: vedi chiaro e continua a credere.",
  "Ciò a cui hai rinunciato troppo presto: riprendilo, o lascialo del tutto."],
  "I Pesci dissolvono; il moto retrogrado lascia schiarire le acque.",
  ["Nel racconto greco, Afrodite ed Eros fuggirono da Tifone.",
   "Si gettarono in un fiume e presero forma di pesci.",
   "Si legarono con una corda per non separarsi.",
   "Nel cielo i due pesci nuotano lontani, uniti da quella corda.",
   "Il nodo è segnato dalla stella Alrescha, «la corda»."],
  "Ciò che hai sognato può chiedere di essere visto con chiarezza."),
}

A = {
'conjunction': ("La congiunzione", "0° · due forze fuse", "Cosa fa una congiunzione", [
  "Due pianeti agiscono come uno: senti di continuo la loro miscela.",
  "Può esserti difficile distinguere le due energie dentro di te.",
  "Sotto transito tende ad aprire un nuovo ciclo di esperienza.",
  "Concentra l'attenzione: puoi riversarti tutto in un solo ambito.",
  "Il tono dipende dai pianeti: può calmare o intensificare.",
  "Puoi non accorgertene, perché ti sembra semplicemente te."],
  "Una congiunzione è un incontro, non una misura.",
  ["Il Tetrabiblos di Tolomeo nomina quattro figure tra i segni.",
   "Opposizione, trigono, quadrato, sestile: forme nel cerchio.",
   "La congiunzione non è una di queste figure.",
   "Era vista come un'unione di corpi, non come uno sguardo.",
   "Gli autori ellenistici parlavano di pianeti presenti insieme.",
   "Due luci nello stesso luogo, che mescolano la loro natura."],
  "Dove due si incontrano, tende a nascere un nuovo inizio."),
'sextile': ("Il sestile", "60° · porte aperte, quieta facilità", "Cosa fa un sestile", [
  "Offre occasioni, ma tende a chiederti di agire.",
  "Colleghi due ambiti della vita con facilità naturale e amichevole.",
  "Conversazioni e contatti possono aprire porte quando ti fai avanti.",
  "I suoi doni sono sottili: senza attenzione rischi di non vederli.",
  "Sotto transito, piccoli sforzi tendono a dare risultati incoraggianti.",
  "Troppa comodità può lasciarne inutilizzata la promessa: fai un passo."],
  "Un sestile bussa piano; sei tu a scegliere di aprire.",
  ["Tolomeo conta il sestile tra le sue quattro configurazioni.",
   "Sessanta gradi: un sesto del cerchio, segni a due di distanza.",
   "Segni dello stesso genere: fuoco con aria, terra con acqua.",
   "Lo chiamava armonico, parente più mite del trigono.",
   "La sua figura è l'esagono tracciato dentro lo zodiaco."],
  "Una porta aperta chiede comunque di essere attraversata."),
'square': ("Il quadrato", "90° · una tensione che cresce", "Cosa fa un quadrato", [
  "Crea attrito tra due bisogni che chiedono entrambi attenzione.",
  "Puoi sentirti spinto ad agire, a costruire o a decidere.",
  "La pressione tende a diventare slancio quando ci lavori.",
  "Sotto transito segna spesso una svolta o una prova.",
  "Evitare il conflitto tende a farlo tornare in forme nuove.",
  "Col tempo può forgiare le tue capacità più forti e la tua resilienza."],
  "Un quadrato è attrito che può diventare movimento.",
  ["Tolomeo conta il quadrato tra le sue quattro configurazioni.",
   "Novanta gradi: un quarto del cerchio, segni a tre di distanza.",
   "I suoi segni hanno genere diverso ma la stessa modalità.",
   "Tolomeo lo giudicava disarmonico, una figura di tensione.",
   "La sua figura è il quadrato tracciato dentro lo zodiaco."],
  "Ciò che ti resiste può essere ciò che ti dà forma."),
'trine': ("Il trigono", "120° · flusso e doni naturali", "Cosa fa un trigono", [
  "Unisce pianeti dello stesso elemento: l'energia scorre facile.",
  "Puoi avere talenti che sembrano senza sforzo, quasi scontati.",
  "Sotto transito tende a portare sostegno, buon tempismo e grazia.",
  "La facilità può diventare una comodità che non ti chiede nulla.",
  "I suoi doni crescono quando li usi in modo consapevole.",
  "Dove i trigoni collegano il tuo tema, tendi a riprenderti in fretta."],
  "Un trigono è un dono; usarlo lo tiene vivo.",
  ["Tolomeo conta il trigono tra le sue quattro configurazioni.",
   "Centoventi gradi: un terzo del cerchio.",
   "Unisce segni a quattro di distanza, della stessa triplicità.",
   "Lo considerava armonico, insieme al sestile.",
   "Fondava queste figure sui rapporti musicali dell'armonia."],
  "Ciò che arriva facile chiede comunque di essere usato bene."),
'opposition': ("L'opposizione", "180° · specchio ed equilibrio", "Cosa fa un'opposizione", [
  "Due pianeti si fronteggiano: ti senti tirato in due direzioni.",
  "Puoi incontrarne un lato attraverso altre persone.",
  "Le relazioni tendono a rispecchiare ciò che non hai ancora fatto tuo.",
  "Sotto transito porta spesso le questioni a un culmine visibile.",
  "L'equilibrio arriva integrando i due lati invece di sceglierne uno.",
  "Il suo dono è la consapevolezza: ti conosci attraverso il contrasto."],
  "Un'opposizione ti mostra te stesso dall'altra parte della stanza.",
  ["Tolomeo conta l'opposizione tra le sue quattro configurazioni.",
   "Centottanta gradi: il diametro del cerchio.",
   "Unisce segni a sei di distanza, uno di fronte all'altro.",
   "Il cerchio diviso a metà, 2 a 1: il rapporto dell'ottava.",
   "Tolomeo la giudicava disarmonica, una figura di contrasto."],
  "Ciò che ti sta di fronte può essere ciò che ti completa."),
'quincunx': ("Il quinconce", "150° · aggiustamento senza facilità", "Cosa fa un quinconce", [
  "Collega due pianeti che non si capiscono facilmente.",
  "Puoi sentire che tra due ambiti servono sempre piccoli aggiustamenti.",
  "Non c'è conflitto aperto, solo uno sfasamento goffo e persistente.",
  "Sotto transito tende a chiedere cambi pratici e nuove regolazioni.",
  "Col tempo impari flessibilità, collegando ciò che sembra estraneo.",
  "Ignorarlo può lasciare la quieta sensazione che qualcosa non torni."],
  "Un quinconce ti chiede di adattarti, non di scegliere.",
  ["Un aspetto minore dell'astrologia più tarda: 150 gradi.",
   "Unisce segni a cinque di distanza, senza nulla in comune.",
   "Non condividono elemento, genere né modalità.",
   "Per gli autori ellenistici questi segni non si vedono.",
   "Il nome latino significa cinque dodicesimi di un intero.",
   "Le quattro figure di Tolomeo non lo includono."],
  "Ciò che non combacia può insegnarti a piegarti."),
}

en = json.load(open('retro_en.json')); ea = json.load(open('aspects_en.json'))
out = {}
for k, v in en.items():
    name, gen, rows, bridge, story, close = S[k]
    assert len(rows) == 8 and 4 <= len(story) <= 6, k
    out[k] = {"title": f"Retrogrado in {name}", "kicker": f"Cosa rivede ogni pianeta quando torna indietro in {name}",
              "secA": f"La revisione {gen}", "rows": [{"p": r["p"], "t": t} for r, t in zip(v["rows"], rows)],
              "bridge": bridge, "secB": f"La storia {gen}", "story": story, "close": close,
              "h1": "Retrogrado", "h2": f"in {name}"}
aout = {}
for k, v in ea.items():
    title, sub, secA, rows, bridge, story, close = A[k]
    assert len(rows) == 6, k
    aout[k] = {"title": title, "sub": sub, "secA": secA, "rows": [{"t": t} for t in rows],
               "bridge": bridge, "secB": "Da dove viene", "story": story, "close": close}
json.dump(out, open('retro_it.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
json.dump(aout, open('aspects_it.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
json.dump({"free": "Tema natale gratuito"}, open('ui_it.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('ok')
